---
title: "SÍNTESE, CONCLUSÃO e PEDIDOS"
format: html
---

## COMENTÁRIO GERAL
Diante disso, **cogita-se haver sofrido violação de direitos humanos**. A Lei é clara em isentar servidor sob impacto de forças autônomas e alheias à sua vontade. Ao perseguir, num juízo administrativo, servidor que enfrentou dificuldades decorrentes de enfermidade, o Senado (ou os servidores específicos) violou a dignidade da pessoa humana e o direito à preservação da própria vida. Diante do sofrimento causado, porque foi relatado em mais de uma situação, a continuidade do procedimento acusatório indevido (conforme se verá adiante), desdobrando-se em mais 3 processos numa escalada de sofrimento, deve caracterizar a prática de tortura psicológica contra inferior hierárquico. A isso soma-se a exposição pública da enfermidade, dos dados de saúde, as publicações oficiais indicando nome, contendo penalizações nao prescritas em leis, a violação de direitos fundamentais (como o direito a defesa e o devido processo), a fabricação de motivo para punir, o direito a férias consumido arbitrariamente, o calculismo frio, a manipulação de prazos para prejudicar o direito a defesa ou a capacidade de finalizar a tese, a ocultação de páginas processuais, as fraudes em processos... Ao todo 16 meses de tortura, causando adoecimento psíquico, físico e financeiro. 

---

## CONCLUSÃO PRINCIPAL 
**O processo foi comprometido/viciado desde o início, quando se deu continuidade a ele. Motivos de nulidade:**
    
  - pelo procedimento de apuração ter sido iniciado para apurar um fato inexistente, um dano não materializado
    
  - pela atuação institucional da DGER e do ILB firmemente para materializar o dano, e ter motivo para punir o servidor
    
  - por ter dentre as práticas perpetradas, a omissão de decidir extrapolando os prazos legalmente estabelecidos e razoáveis, a retenção de processos indefinidamente sem decisão, a determinação hierárquica de retenção processual a subordinados, o impedimento de acesso da defesa do servidor ao processo, a inclusão de acusações no proprio relatório da decisão sem possibilidade de defesa ou contestação, a sujeição do servidor a procedimento de acusação infundado durante 1 ano e 2 meses de postergação injustificada em demonstração de abuso processual e ineficiência administrativa, a **insegurança jurídica** instaurada **sobre o último ano de doutorado do servidor** e **sobre o período "concedido" de prorrogação**, durante o qual o servidor deveria estar dedicado à elaboração e finalização de sua tese, mas teve a produtividade afetada mediante as ameaças de corte salarial, de PAD e até mesmo de exoneração, a conivência silenciosa e subserviente dos quadros de servidores envolvidos que falharam quanto à necessidade de denúncia a superior dos indícios de irregularidades e de crime; a perseguição a servidores que, durante o curso do processo, se posicionaram contra as irregularidades; a disposição de outros servidores em dar andamento a ordens superiores irregulares, dentre outras práticas aqui evidenciadas 
    
  - por não ter motivação factual nem jurídica. 
    
  - por alegar descumprimento de afastamento ou não aproveitamento de curso sem que o curso haja terminado, é inadequado, como a DGER mesma afirmou em um momento do processo, apesar de logo em seguida praticá-lo em forma de assédio e perseguição
    
  - por ter sido continuidado sem materialidade alguma
    
  - por até hoje não conseguirem definir qual foi o artigo infringido pelo servidor
    
  - porque cada peça processual concluir com um artigo diferente do RASF ao motivar ou sugerir punição
    
  - por acusações vagas (descumprimento, de quê?)
    
  - pelas alegações genéricas (nos termos do art... tá, mas em que sentido?)
    
  - pelo uso da expressão 'nos termos de tal lei' ou "art." para parecer legítimo, mas citar normas desconexas
    
  - pela estratégia frequente de citarem normas sem pertinência com o que é discutido ou decidido logo em seguida
    
  - pelo uso de normas revogadas para tentar punir o servidor
    
  - pelo procedimento iniciado para perseguir, em pleno afastamento
    
  - (cont.) pois se há prazo de afastamento, ainda não há hipótese de punição
    
  - (cont.) porque há prazo para concluir o curso
  - porque DGER só tem competência p/ suspender a 30 dias, advertir e multar
    
  - porque DGER não tem jurisdição sobre órgãos legislativos
    
  - porque a pena aplicada não existe nas normas
    
  - porque a DGER não observou o rito processual, com as formalidades necessárias para garantir o devido processo e a ampla defesa
    
  - porque a DGER induziu nas perguntas que fez as respostas que o ILB deveria dar
    
  - porque cassação parcial de afastamento para pós-graduação não existe no regime disciplinar da 8112 nem no RASF
  - porque a DGER questionou o servidor sobre documentos custodiados pela própria Administração
    
  - porque não havendo motivo para punir, retiveram o processo parado até fabricarem um motivo
    
  - porque fui impedido de me manifestar no processo
    
  - porque fui ignorado sumariamente em pedidos de carga para me manifestar
    
  - porque fui ignorado em pedidos de informação sobre minha situação pessoal 
    
  - porque depois de minha manifestação prévia, nunca mais tive acesso ao processo
    
  - porque minhas indagações, arguições de suspeição dos envolvidos, pedidos de esclarecimentos, reclamações de irregularidades não encontraram qualquer ressonância na DGER, sendo ignoradas sem receber qualquer tratativa;
    
  - porque documentos foram fraudulentamente retirados e substituídos dos processos sem deixar rastro
    
  - porque folhas foram ocultadas sob alegação de sigilo
    
  - porque outras folhas com informações sensíveis foram mantidas à mostra, mesmo após solicitação
  
  - porque seguraram o processo sem decisão até vencer meu prazo de afastamento
    
  - quando venceu, para então me acusaram de descumprimento, por não ter concluído e não ter apresentado os documentos em comprovação da conclusão
  
  - ou seja: (me perseguiram antes de eu terminar + obstaculizaram o processo injustificadamente + até vencer afastamento + me acusaram de descumprir) =  fabricaram o motivo para me acusar
    
  - porque o [rito processual](A ordem parece ser: instrução encerrada, passa a manifestação prévia, feita a instrução, passa ao relatório; de lá, é encaminhado para decisão
    
  - No caso, encerrada a instrução, veio para manifestação. Feita manifestação (com suspeição arguida contra órgão de monitoramento), processo retornou ao **órgão arguido** para instrução **de novo**, onde ficou retido por 72 dias e só recebeu parecer do órgão quando venceu o afastamento. O parecer simplesmente replicou todos os meus argumentos, o que entendo ser concordância. Aí seguiu para DGER onde deveria ter sido decidido. Mas ficou 80 dias parado e ainda não obteve decisão. Foi para o ILB mais uma vez, (enquanto foi e voltou 2 vezes no outro processo) e só então foi finalmente devolvido para a DGER e decidido. Ao que me parece, não compete à instância decisória interferir no relatório. Se discorda, fundamenta a decisão e diz em quê o relatório é contradito pelas evidências - mas decide! Entre idas e vindas, o processo sobre o 1º semestre de 2023 só obteve decisão à beira do recesso de Natal e Ano Novo, fui notificado em janeiro da decisão, para manifestação até 5 de fevereiro. Sendo que o prazo que ela tinha me dado para concluir a tese era 27 de janeiro. Ou seja, ou concluía a tese ou me defendia. OU nenhum dos dois, que foi o que aconteceu.
  
  - porque no meio desse contexto, vi documentos do processo começarem a desaparecer. Uns retirados literalmente do processo e substituídos por outros - porque creio que comprometedores especialmente quanto à imparcialidade do juízo, e outros ocultados sob argumento de sigilo - enquanto minhas informações de saúde continuam públicas, e já circularam em e-mail internamente. Então parece que os prazos têm sido meio que orquestrados para me prejudicar com as coincidencias de prazos finais urgentes e improrrogáveis) não foi observado: nem em suas formalidades, nem na ordem das etapas, nem nos prazos (principalmente), nem quanto à garantia do direito à defesa. 

  - porque adicionaram tardiamente acusações no relatório e na própria decisão final, fases em que não foi permitido ao servidor se defender no processo, mesmo após pedido expresso por escrito

  - porque DGER encaminhou processo para novas manifestações do ILB sem que houvesse fato novo a apurar

  - porque ILB mudou conclusão da manifestação sem fato novo a apurar

  - porque ILB reeditou análises sobre fatos antigos, acrescentou questões interessantes até, mas não me deram oportunidade de contestar

  - porque a DGER não deu nome ao procedimento administrativo que seguiu-se  para apuração, o que definiria o rito processual a seguir. Não disse: é sindicância, nem é PAD, nem nenhuma outra categoria. Assim, começou com apuração preliminar, e, dentro do próprio âmbito da apuração preliminar aplicou punição típica de PAD, mas que durou o tempo equivalente a processo de inventário com partilha de bens litigiosa.

  - porque não é eficiente nem razoável um processo de monitoramento que na metade do curso (faltando 2 anos) já acumulava 1000 mil páginas e, para apurar irregularidade inexistente, chegue a 1800 páginas. Mil e oitocentas páginas de acompanhamento que toma tempo e dedicação que deveriam estar direcionados à tese. É uma atuação ineficiente, antieconômica, antijurídica e avessa ao interesse público, contrária aos próprios princípios estabelecidos na política de capacitação inscrita no Regulamento Administrativo, e na Constituição.

---


