---
title: "A Regularidade do Afastamento e o Interesse Público"
format: html
---

O presente memorial tem por finalidade apresentar, de forma sistemática, os principais elementos normativos, administrativos e fáticos que envolvem o caso de **servidor do Senado Federal afastado para cursar programa de pós-graduação stricto sensu (doutorado)**, em instituição pública de ensino superior no Brasil, nos termos do **art. 96-A da Lei nº 8.112/1990**.

O afastamento foi solicitado inicialmente em **18 de março de 2020**, tendo como objetivo a participação no curso de doutorado em Ciência Política na Universidade de Brasília (UnB). Em conformidade com o marco legal, o processo administrativo que analisou o pedido foi submetido à apreciação de diversas instâncias da estrutura do Senado Federal:

## **Chefia Imediata**: favorável ao afastamento  
  A chefia do servidor manifestou-se nos autos expressamente **favorável ao pedido de afastamento**, conforme exigido pelo Anexo IV do RASF. Tal manifestação foi detalhada no processo administrativo, destacando que:
  
  > "Os objetivos do servidor, ao pleitear a participação no referido programa de doutorado, alinham-se com a missão institucional do DataSenado [...]" (p. 178, NUP 00200.003561/2020)

## **Chefia imediata**: há interesse comum na formação pretendida pelo servidor
  [A chefia também confirmou que a **área de conhecimento da ação de capacitação se enquadra nas áreas temáticas de interesse comum** a todos os cargos/especialidades do Senado Federal (conforme Anexo II do Ato Conjunto DGER/ILB/SEGP nº 1/2018), além de ser compatível com as **atribuições específicas do cargo ocupado pelo servidor**, cuja exigência de ingresso incluía formação em Ciência Política ou áreas afins](p. 178, NUP 00200.003561/2020).

## **Chefia imediata**: garantidos ajustes para não haver ônus adicional à Administração Pública
  Em conformidade com as [normas internas](Art. 35. A concessão de afastamento de servidor do Senado Federal para participar de programas de pós-graduação stricto sensu não acarretará ônus adicional \(...\), RASF, ATC 14/2022), ao autorizar o afastamento, a chefia imediata declara que a **ausência do servidor não implicará a necessidade de pagamento de horas extras para a equipe, nem a contratação de substituto**, e que suas funções foram redistribuídas internamente, o que **elimina qualquer ônus adicional à Administração Pública durante o período do afastamento**.

## **Secretaria de Gestão de Pessoas (SEGP)**: servidor atende os requisitos e curso é compatível com cargo 
  A SEGP emitiu pareceres técnicos favoráveis ao afastamento, com base no art. 96-A da Lei nº 8.112/90. [Em um, reconheceu que o servidor atendia todos os requisitos legais e regulamentares exigidos, estando apto para o afastamento pleiteado](pp. 180 a 186, Processo NUP 00200.003561/2020, ou também NUP 00100.086462/2020). No outro, analisou e constatou que [a ação de capacitação pleiteada era compatível com o cargo e especialidade ocupados pelo servidor, observando a pertinência temática com base no Ato do 1º Secretário nº 3/2014. Assegurou também que há "enquadramento da temática da capacitação nas condições previstas no art. 5º do Anexo IV do RASF (Resolução nº 13/2018) c/c art. 2º do APS 3/2014, na Matriz Geral de Correlação (Ato Conjunto DGER, ILB e SEGP nº 1/2018), “Ciência Política” é área do conhecimento de interesse do Senado Federal comum a todas as especialidades, área relacionada com a capacitação pretendida"](p. 188, Processo NUP 00200.003561/2020, ou também NUP 00100.088391/2020).

## **Instituto Legislativo Brasileiro (ILB)**  
  Por causa da pandemia de COVID-19, o processo de solicitação do afastamento foi impedido de continuar tramitando, em vista de proibição editada no Senado de que servidores participassem de cursos presenciais. Embora as aulas tenham começado em março de 2020, o processo ficou com tramitação suspensa até agosto de 2020. O pedido de afastamento só voltou a tramitar após a juntada da [**Resolução CEPE nº 59/2020 da UnB**]^(https://dpg.unb.br/images/Resolu%C3%A7%C3%A3o_CEPE_N%C2%BA_0059_2020.pdf), que **estabelecia as aulas à distância** (art. 2º, da Res CEPE nº 59/2020 da UnB) e **prorrogava os prazos dos cursos de pós-graduação** em razão da pandemia da COVID-19 **por período equivalente**, pelo menos, ao tempo em que as aulas ficaram suspensas e na modalidade à distância. **Ciente da Resolução da UnB, o ILB reconheceu a regularidade do pedido e manifestou-se favoravelmente ao afastamento (pp. 624 a 629, Processo NUP 00200.003561/2020, ou também NUP 00100.106506/2020)**.  
  O parecer do ILB também deixou registrado que o afastamento deveria observar as obrigações previstas nos arts. 40 e 41 do Anexo IV do Regulamento Administrativo do Senado Federal, conforme a **Resolução nº 13/2018**.  
  Importa ressaltar que o ILB considerou detalhadamente a Resolução CEPE nº 59/2020 da UnB e recomendou que, independente dos prazos solicitados, seja necessário que o servidor conclua o curso de doutorado integralmente como condição para a regularidade do afastamento, conforme exige a legislação.

- **Comitê Científico-Pedagógico do ILB**  
  Reunido em **06 de novembro de 2020**, o Comitê analisou o mérito do programa de doutorado à luz da documentação apresentada, inclusive da Resolução CEPE nº 59/2020 e os efeitos da pandemia sobre as atividades acadêmicas e o calendário letivo na UnB. O Comitê proferiu **parecer favorável** ao afastamento, reconhecendo a compatibilidade temática, a qualificação institucional do curso, e a adequação do plano de estudos às diretrizes da capacitação estratégica do Senado.
  
- **Presidência do Senado Federal**  
  A autorização final foi formalizada pelo Presidente da Casa em **26 de fevereiro de 2021**, ratificando o entendimento dos órgãos técnicos, corroborando o interesse público na formação do servidor chancelando a legalidade do afastamento conforme os critérios da **Lei nº 8.112/1990**, da **Resolução nº 13/2018** e do **Regulamento Administrativo do Senado Federal**.

- **Diretoria-Geral (DGER)**  
  Com base nos pareceres acima e na legislação aplicável, a Diretoria-Geral **deferiu o pedido** em 31 de março de 2021 (NUP 00100.030498/2021-40), estabelecendo o período de afastamento entre **24 de outubro de 2020 e 16 de agosto de 2024**, na modalidade de **ônus limitado**, ou seja, com manutenção apenas das parcelas remuneratórias ordinárias.

O conjunto desses pareceres evidencia que o afastamento foi **plenamente regular**, analisado sob a ótica da legalidade, da oportunidade administrativa e da compatibilidade institucional. Todos os órgãos competentes concluíram pela **conformidade da solicitação com os requisitos normativos**, especialmente no que tange à compatibilidade temática, à inexistência de impedimentos funcionais e à demonstração de existir interesse público na capacitação do servidor, fato corroborado ainda pela concordância expressa do Presidente do Senado (.

Este memorial passa, a seguir, à exposição dos fatos, fundamentos jurídicos e elementos probatórios que sustentam a defesa do servidor, com especial atenção às **irregularidades identificadas no curso do processo administrativo**, inclusive no tocante a interpretações normativas incorretas e ocultações documentais prejudiciais à ampla defesa.
