---
title: "Untitled"
format: html
---

1 a 7 - formulários
16 a 22 - regulamento do ppgcp

                    Art. 26 - 0(a) aluno(a) de doutorado deverá ser aprovado(a) em exame de qualificação, o qual consistirá 
                    de defesa do projeto de tese de doutorado e de arguição oral sobre temas na área de concentração da tese.
                    § 15 o Exame de Qualificação deverá ser realizado nos 60 primeiros dias do quinto período letivo 
                    regular, não incluindo Trancamento Geral.
                    § 25 Cabe ao(à) orientador(a) entrar em contato com a Comissão para marcar a data de defesa, 
                    com antecedência mínima de 2 (duas) semanas.
                    § 35 Constarão da Banca Examinadora: o(a) orientador(a), 1 (um) membro vinculado ao programa, 
                    l(um) membro não vinculado ao programa e 1 (um) membro suplente vinculado ao Programa.
                    § 45 Após o aluno ter sido aprovado no Exame de Qualificação, o(a) orientador(a) poderá marcar a 
                    data de Defesa da Tese, em prazo não inferior a 2 (dois) meses do Exame de Qualificação.
                    Art. 29 - A Defesa de dissertação de mestrado ou tese de doutorado será requerida, por escrito, pelo(a) 
                    professor(a) orientador(a), com uma antecedência mínima de 30 (trinta) dias da data da defesa.
                    § 15 Deverá ser anexada a ata de aprovação do Exame de Qualificação e, no caso dos estudantes de 
                    doutorado, os comprovantes de publicações, de acordo com o previsto no Art. 285.
                    § 25 A solicitação deverá ser encaminhada ao Presidente do CCPG/IPQL, que homologará a data de 
                    realização e a constituição da Comissão Examinadora, encaminhando-as à Câmara de Pesquisa e Pós- 
                      Graduação (CPP).
                    § 35 Uma cópia da dissertação ou da tese a ser defendida deverá ser entregue a cada membro da comissão 
                    examinadora com antecedência mínima de 30 (trinta) dias do prazo proposto para a defesa.
                    Art. 28 - Para obter o diploma de Doutor(a) em Ciência Política, além de cumprir as exigências da legislação 
                    em vigor e as normas da Universidade de Brasília, o(a) aluno(a) deverá cumprir os seguintes requisitos:
                      I - Publicar dois artigos acadêmicos em revistas especializadas ou anais de congressos acadêmicos 
                    de ciência política ou áreas afins até o final do sétimo período letivo;
                    I I- 
                      Defender tese, de sua autoria exclusiva, em sessão pública, aprovada por uma Comissão
                    Examinadora

127 a 144 - pré projeto da tese

158 a 166 - Resolução CEPE 59/2020 
            
            Art. 6º, §3º 0 semestre 1/2020 não contará para os limites de permanência máxima dos (das)
            estudantes.
            
            Art. 7º 0 colegiado de curso de pós-graduação deverá prorrogar os prazos finais para a defesa de dissertações e teses dos estudantes atualmente vinculados aos respectivos programas, subtraindo dos prazos regimentais ao menos o período de suspensão do calendário e o período realizado de forma não presencial.      
            00100.075779/2020-41-2
      
      OBS: Esta Resolução é do conhecimento do Senado desde antes de eu iniciar o curso, está presente na documentação que dá início ao processo e foi apresentada antes até mesmo do edital de seleção. Ou seja, os termos já estavam dados desde antes, e quando o Senado aprovou o meu afastamento, aprovou aquiescendo àquelas condições. A aprovação ocorreu nos termos dos documentos apresentados. 

167 a 174 - Edital de seleção do PPGCP

175 a 178 - 2º formulário de requisição de afastamento para cursar o doutorado.
          - p. 175: diz qual é a norma que regerá o afastamento: Atualmente (17/08/2018) consolidado pela Resolução do Senado Federal n^ 13/2018. Considerar a última atualização da norma no dia do requerimento.          
          - P. 176: prazo indicado no formulario - 24/10/2020 a 16/08/2024.

179 - Termo de Compromisso firmado no ato do pedido de afastamento. Declara estar ciente das disposições contidas nos arts. 95 e 96-A da Lei n^ 8.112/90 e no Anexo IV do Regulamento Administrativo do Senado Federal (RASF), no tocante às condições exigidas para a concessão de afastamento para participação em programa de pós-graduação stricto sensu no país ou no exterior^ que incluem as seguintes obrigações: 

      1. Após 0 deferimento do pedido e enquanto durar o afastamento, na periodicidade a ser definida pelo Senado Federal, conforme a conveniência e necessidade da Casa (art. 40, do Anexo IV, do RASF):  a) enviar ao Instituto Legislativo Brasileiro relatório de atividades acadêmicas, incluindo eventual produção acadêmica já realizada;b) enviar ao Instituto Legislativo Brasileiro comprovante de frequência no curso quando solicitado;c) prestar outras informações a respeito das atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro.2. Após 0 afastamento, quando do retorno às atividades no Senado Federal, após a conclusão do curso (art. 41, do Anexo IV, do RASF e Inciso II, art. 12, da Portaria do ILB n^ 1/2017):a) entregar, em até 60 (sessenta) dias após a conclusão do programa, cópia da dissertação ou tese aprovada para a obtenção da titulação;b) elaborar e executar ação de disseminação e aplicação do conhecimento adquirido na pós-graduação, quando requisitado pelo Instituto Legislativo Brasileiro, nos termos do § 8^ do art. 19 e art. 57 do Anexo IV do RASF;c) prestar outras informações a respeito das atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro.3. Ressarcimento ao Senado Federal em montante a ser arbitrado pelo Conselho de Supervisão do ILB, limitado ao valor proporcional correspondente ao incentivo para o afastamento concedido, nos casos de (art. 42, do Anexo IV, do RASF):  a) desistir, sem motivo justificado, da ação de capacitação motivadora do afastamento; b) durante o afastamento, aposentar-se voluntariamente, solicitar exoneração, tomar posse em outro cargo inacumulável;c) não permanecer no serviço público federal, na condição de servidor ativo, por período mínimo equivalente ao afastamento concedido, contado da data de retorno do servidor;d) não obter o título que justificou o afastamento, salvo na hipótese comprovada de força maior ou de caso fortuito, na forma da lei;e) não cumprir as obrigações contidas no item 2 deste Termo de Compromisso.Assumo, ainda, total responsabilidade pelas informações por mim prestadas nos autos, sob pena das sanções administrativas, civis e penais cabíveis.
      arts. 95 e 96-A da Lei n^ 8.112/90 e no Anexo IV do Regulamento Administrativo do Senado Federal (RASF)
      art. 40, do Anexo IV, do RASF
      art. 41, do Anexo IV, do RASF e Inciso II, art. 12, da Portaria do ILB n^ 1/2017
      § 8^ do art. 19 e art. 57 do Anexo IV do RASF;
      Art. 42, do Anexo IV, do RASF
      
180 - Parecer SEGP:  00100.086462/2020-30
      
      Analisa o pedido, e aponta a lei que prevê e regula o afastamento:
                  Art. 96-A.  O servidor poderá, no interesse da Administração, e 
                desde que a participação não possa ocorrer simultaneamente com 
                o exercício do cargo ou mediante compensação de horário, 
                afastar-se do exercício do cargo efetivo, com a respectiva 
                remuneração, para participar em programa de pós-graduação 
                stricto sensu em instituição de ensino superior no País.  
                § 1o Ato do dirigente máximo do órgão ou entidade definirá, em 
                conformidade com a legislação vigente, os programas de 
                capacitação e os critérios para participação em programas de pós
                graduação no País, com ou sem afastamento do servidor, que 
                serão avaliados por um comitê constituído para este fim.  
                § 2o Os afastamentos para realização de programas de 
                mestrado e doutorado somente serão concedidos aos 
                servidores titulares de cargos efetivos no respectivo órgão ou 
                entidade há pelo menos 3 (três) anos para mestrado e 4 (quatro) 
                anos para doutorado, incluído o período de estágio probatório, 
                que não tenham se afastado por licença para tratar de 
                assuntos particulares para gozo de licença capacitação ou 
                com fundamento neste artigo nos 2 (dois) anos anteriores à 
                data da solicitação de afastamento.  
                § 3o Os afastamentos para realização de programas de pós
                doutorado somente serão concedidos aos servidores titulares de 
                cargos efetivo no respectivo órgão ou entidade há pelo menos 
                quatro anos, incluído o período de estágio probatório, e que não 
                tenham se afastado por licença para tratar de assuntos 
                particulares ou com fundamento neste artigo, nos quatro anos 
                anteriores à data da solicitação de afastamento.  
                § 4o Os servidores beneficiados pelos afastamentos previstos nos 
                §§ 1o, 2o e 3o deste artigo terão que permanecer no exercício de 
                suas funções após o seu retorno por um período igual ao do 
                afastamento concedido.  
                § 5o Caso o servidor venha a solicitar exoneração do cargo ou 
                aposentadoria, antes de cumprido o período de permanência 
                previsto no § 4o deste artigo, deverá ressarcir o órgão ou entidade, 
                na forma do art. 47 da Lei no 8.112, de 11 de dezembro de 1990, 
                dos gastos com seu aperfeiçoamento.  
                § 6o Caso o servidor não obtenha o título ou grau que justificou 
                seu afastamento no período previsto, aplica-se o disposto no § 5o 
                deste artigo, salvo na hipótese comprovada de força maior ou de 
                caso fortuito, a critério do dirigente máximo do órgão ou entidade.  
                § 7o Aplica-se à participação em programa de pós-graduação no 
                Exterior, autorizado nos termos do art. 95 desta Lei, o disposto nos 
                §§ 1o a 6o deste artigo. (grifos nossos)
      
      Relativamente ao ônus, o anexo IV do Regulamento 
      Administrativo do Senado Federal (Política de Capacitação), alterado pela 
      Resolução nº 13, de 2018, entendemos que o pleito atende ao disposto no art. 
      35, conforme a seguir:  
      
                Art. 35. A concessão de afastamento de servidor do Senado 
                Federal para participar de programas de pós-graduação, 
                stricto sensu, ocorrerá na modalidade ônus limitado, sendo 
                devido o pagamento apenas da parcela prevista no inciso I do 
                § 2º do art. 29 deste Anexo, salvo autorização excepcional do 
                Presidente do Senado Federal, ouvido o Conselho de Supervisão 
                do ILB^(Art. 29. As modalidades de participação do Senado Federal no apoio financeiro à participação de servidores em ações externas de capacitação são as seguintes:  I – com ônus total, sendo devido o pagamento de todas as parcelas previstas no § 2º deste       artigo.  II – com ônus limitado, sendo devido o pagamento das parcelas previstas nos incisos I e II do § 2º deste artigo. § 2º O servidor participante de ações externas de capacitação que impliquem ônus poderá receber as seguintes parcelas:  I – todas as parcelas remuneratórias ordinárias relativas a seu cargo e nível na carreira)
                Art. 39. A concessão de afastamento para participação de 
                programas de Pós-graduação Stricto Sensu depende do 
                cumprimento dos seguintes requisitos pelo servidor: 
                  I – exercer cargo efetivo no Senado Federal pelo período 
                mínimo de três anos para mestrado e quatro anos para 
                doutorado ou pós-doutorado;
                II – assinatura de termo de compromisso de permanência no 
                Senado Federal, na condição de servidor ativo, por período 
                mínimo equivalente ao período concedido, contado da data de 
                retorno do afastamento; 
                III – não tenha idade para ser alcançado pela aposentadoria 
                compulsória no espaço de tempo entre o início do curso de pós
                graduação e o término do período a que se refere o inciso III deste 
                artigo;  
                IV – não tenha se afastado para participação em programa de 
                mestrado ou doutorado nos últimos 2 anos ou, para programa 
                de pós-doutorado, nos últimos 4 anos anteriores à data da 
                solicitação do novo afastamento; 
                V – encontre-se em efetivo exercício no período de inscrição e 
                não esteja afastado para exercício de mandato eletivo ou para 
                servir em organismo internacional de que o Brasil participe ou com 
                o qual coopere; 
                VI – não tenha descumprido qualquer obrigação assumida em 
                função de afastamentos anteriores, sem que as justificativas 
                tenham sido aceitas pelo Senado Federal.
                
184 a 187 - no parecer SEGP dá ciência à DGER de que houve adiamento do curso, em função da Pandemia de COVID19. 


                IMPORTANTE: O pedido original era de 18 de março de 2020. 
                Senado vedou a participação de servidores em cursos presenciais, permanecendo o servidor impedido de iniciar seus estudos até agosto de 2020, quando a UnB adotou aulas à distância.
                Ainda assim, a SEGP exigiu cumprimento de prazo prévio de 30 dias para poder solicitar participação em atividade de capacitação no país.
                Isso causou mais 30 dias de atraso ao início do curso, uma vez que, apesar de se tratar do mesmo pedido, de autorização para o mesmo curso que iria se iniciar em março, a SEGP deu tratamento como se fosse outra solicitação. 
                
      
188                -  "No que se refere ao enquadramento da temática da capacitação nas condições previstas 
                no art. 5º do Anexo IV do RASF (Resolução nº 13/2018) c/c art. 2º do APS 3/2014, na Matriz 
                Geral de Correlação (Ato Conjunto DGER, ILB e SEGP nº 1/2018), “Ciência Política” é área 
                do conhecimento de interesse do Senado Federal comum a todas as especialidades, área 
                relacionada com a capacitação pretendida. "      
                
189            "Há compatibilidade entre a ação de capacitação pretendida e o cargo/especialidade 
                ocupado pelo requerente, com fulcro no inciso II do art. 2º do Ato do 1º Secretário nº 3, de 
                2014, c/c art. 5º do Anexo IV da Resolução nº 13 de 2018."
      
193             00100.100088/2020-92 : declaração da universidade em 26/10/2020 de que o curso tem previsão de término em **julho de 2024**. "Declaramos, também, que os Cursos de Doutorado exigem de seus alunos **dedicação exclusiva**, 
                pela necessidade de **estudos, de pesquisa, além de horas-aula em disciplinas**".
                
194-195         E-mail já afirmava atuação do SEPOS prejudicando estudos do servidor em 2020, quando cobrava um dia específico para o término do curso, sem que a Universidade fornecesse essa informação somente de semestre em semestre:
                    
                    O problema com as datas é que não existe calendário acadêmico de 2024 ainda - veja que a própria 
                    Secretaria não especificou dias, ela fez referência a meses na declaração. 
                    A UnB publica semestralmente o calendário acadêmico daquele mesmo semestre e só então vamos saber 
                    a data de início e término daquele período - o que não é possível antecipar em relação ao ano de 2024. 
                    O que há de fato e de concreto é o regulamento do curso que estipula o limite de permanência mínimo e o 
                    limite de permanência máximo - o que passa disso é estimativa.  
                    Notem ainda que **a despeito da indefinição das datas e de estar sendo prejudicado porque o curso já 
                    começou, o período de afastamento que solicito no processo é menor do que o período previsto na 
                    legislação**.      
                
                Messias:  00100.100092/2020-51 p.195 "Recebemos o seu email com a declaração da UnB. Na sua segunda solicitação de afastamento, em virtude da mudança provocada pela pandemia, vc alterou o afastamento para de  24 de outubro a 10 de agosto de 2024. Essas datas aparecem onde no documento que vc enviou? Elas coincidem com alguma disciplina que vc vai cursar? Em suma, queremos saber qual a justificativa para essas novas datas."
                
>                OBS: sabia que o prazo de duração era 48 meses, pelo regulamento. Eu simplesmente havia postergado o fim do curso, por não ter começado ainda. Projetei de agosto de 2020 a agosto de 2024, com base no regulamento que estipula 48 meses de curso. A pergunta de Messias revela não só sua arbitrariedade, como tambem revela descontentamento em relação ao deslocamento do prazo. Isso indica que esperava que eu mantivesse o mesmo prazo apesar do atraso administrativo, revelando na verdade se tratar de estratégia para reduzir o tempo de estudo dos servidores.
                    Eu já havia preenchido o formulário duas outras vezes. Em nenhuma delas me perguntou sobre como havia sido definida a data de término do curso, só nessa.

624 - somente em 06 de novembro de 2020 o ILB encaminha minha solicitação para deliberação do diretor do órgão.
                  Nesse mesmo documento, o ILB reafirma quais são as minhas obrigações e deveres:
                  "6. No documento nº 00100.031237/2020-66, o servidor juntou termo de compromisso, 
                  declarando estar ciente das disposições contidas no Anexo IV do Regulamento 
                  Administrativo do Senado Federal (consolidado pela Resolução do Senado Federal nº 
                  13/2018), bem como na Lei nº 8.112/1990, e tomando conhecimento das condições e das 
                  obrigações exigidas para o afastamento solicitado."p.626  00100.100398/2020-15 
                  A conformidade às normas do Senado:
                  "o pedido de afastamento para participação em programa de pós-graduação stricto sensu no Brasil, por parte do 
                  servidor-requerente, cumpre os requisitos estabelecidos no parágrafo 2º do art. 96-A da Lei 
                  nº 8.112/1990, bem como o que dispõe os arts. 27, 39 e 51 do Anexo IV do Regulamento 
                  Administrativo do Senado Federal (consolidado pela Resolução do Senado Federal nº 13/2018)."               
                  
                  "documento nº 00100.088391/2020-18, foi juntada decisão favorável do Coordenador 
                  de Políticas de Pessoal que atesta a compatibilidade entre a ação de capacitação pretendida 
                  e o cargo/especialidade ocupado pelo servidor, conforme estabelece o art. 5º do Anexo IV 
                  do Regulamento Administrativo do Senado Federal (consolidado pela Resolução do 
                  Senado Federal nº 13/2018)".p.627 00100.100398/2020-15   
                  
                  trecho importante porque mais uma vez comprova a ciência do Senado em relação às condições que ensejaram a mudança de prazo e as dificuldades inerentes à pandemia, 
                  as quais perduraram ainda por mais 2 anos!! Também relata a proibição, no Senado, de participação em ensino presencial.
                  "10.  Inicialmente, o pleito do requerente para afastamento dizia respeito ao período de 17 de 
                  abril de 2020 a 31 de dezembro de 2023 (documento nº 00100.031237/2020-66). Contudo, 
                  posteriormente o servidor juntou aos autos a Resolução do Conselho de Ensino, Pesquisa 
                  e Extensão da UnB nº 0059/2020 (doc. nº 00100.075779/2020-41), datada de 28 de julho 
                  de 2020, que dispõe sobre o planejamento e execução de atividades de ensino
                  aprendizagem de forma não presencial e em caráter emergencial nos cursos de graduação 
                  e pós-graduação durante a pandemia do Covid-19. Entre as providências adotadas, está a 
                  realização de aulas somente na modalidade on-line (de forma síncrona e assíncrona) 
                  enquanto perdurar a fase 1 do isolamento social devido à pandemia, além da alteração do 
                  calendário escolar dos cursos de graduação e de pós, com flexibilização da frequência das 
                  disciplinas teórico-práticas, entre outras medidas. 
                  11. As providências de isolamento social e adoção da modalidade on-line para os cursos 
                  oferecidos, adotadas pela UnB mediante a Resolução nº 0059/2020, citada no item anterior, 
                  enquadram o pleito do requerente ao que havia sido estabelecido para servidores do Senado 
                  como medidas de proteção e isolamento social devido à pandemia pelo **Ato da Diretoria
                  Geral do Senado (ADG) nº 05/2020**. O referido ato, em seu artigo segundo, determina:"  
                              “ficam suspensas as autorizações para participação, no 
                              país, de missão oficial, atividades de capacitação,
                              competições desportivas e licenças capacitações na 
                              modalidade presencial.(grifo nosso)” 
                  "12. Uma declaração da UnB foi apresentada pelo servidor, no documento nº 
                  00100.100088/2020-92, destacando que para o curso de doutorado naquela instituição o 
                  tempo máximo de permanência é de 48 meses.  A declaração cita que o servidor iniciou o 
                  curso de doutorado em março de 2020, mas devido à pandemia a supramencionada 
                  Resolução da UnB nº 0059/2020 definiu que o primeiro semestre de 2020 não contará para 
                  os limites de permanência máxima dos estudantes, motivo pelo qual o curso do requerente 
                  tem previsão de término para julho de 2024. " p.627-628 - 00100.100398/2020-15
  OBS: No item 13 o ILB afirma inexistir edital (de seleção interna para participação na pós-graduação), 
  não sendo cumprida, portanto, a **PIL 01/2017**
                  "13. Em vista do exposto, há que se ponderar sobre:  
                  a) o Plano de Capacitação e Desenvolvimento dos Servidores do Senado Federal (PCASF) 
                  2020, que ainda não foi aprovado; 
                  b) a inexistência de instrumento editalício em cumprimento à Portaria do ILB nº 01/2017; 
                  c) o atendimento dos requisitos legais, por parte do requerente, atestados pela Secretaria de 
                  Gestão de Pessoas; 
                  d) o endosso das chefias à solicitação de afastamento; 
                  e) a qualidade do programa de estudos; 
                  f) a modalidade de ensino adequa-se às determinações do ADG nº 05/2020; 
                  g) a duração do afastamento requerido ser correspondente à duração regular do programa;" 
Nesse próximo trecho, em novembro de 2020, o ILB recomenda que o não deve ser eximido de cumprir as obrigações dispostas nos arts. 40 e 41 do Anexo IV do Regulamento Administrativo do Senado Federal (consolidado pela Resolução do Senado Federal nº 13/2018) e 
de concluir a integralidade do doutorado requerido.Em outras palavras, sem que o servidor tivesse sequer se ausentado para ir a aulas, e enquanto o Senado não tinha decidido nada sobre o afastamento, 
já com um mês de atraso em relação ao início previsto do afastamento e três meses de atraso em relação ao reinício das aulas, o ILB ainda não tinha decidido se ia encaminar o pedido do servidor ou não, mas já falava em não permitir mais tempo para o servidor concluir o curso.                           
                  "não exima o 
                  servidor de cumprir as obrigações dispostas nos arts. 40 e 41 do Anexo IV do Regulamento       
                  Administrativo do Senado Federal (consolidado pela Resolução do Senado Federal nº 13/2018) e 
                  de concluir a integralidade do doutorado requerido". p.629   00100.100398/2020-15
                  
631 - 632        "A requisição, com ônus limitado para o Senado Federal, fundamenta-se pelo artigo 96- A 
                  da Lei n° 8.112/90 e no Anexo IV, Capítulo V, artigo 35, §1° e §2°', do Regulamento 
                  Administrativo do Senado Federal (Política de Capacitação e Desenvolvimento dos Servidores do 
                  Senado Federal)" (...)  
                  "o Comitê Cientifico-Pedagógico do ILB, em reunião realizada no dia 
                  06/11/2020, manifestou-se favoravelmente ao afastamento. Dessa forma, **com base nas informações 
                  acostadas nos autos**, sugiro o encaminhamento à Diretoria-Geral para conhecimento/providências 
                  que se fizerem necessárias, nos termos do Anexo IV, Capitulo V, artigo 36, § 3°^, inserido no RASF 
                  acima referido." 26/11/2020 p.631-632 - 00100.106506/2020-55                                   
                  
633 - Presidente autoriza em 26/02/2021- embora a DGER já pudesse ter autorizado desde há muito tempo. p.633 00100.030498/2021-40

634 - 638         Deferimento pela DGER, somente em 31/03/2021: "cumpre os requisitos estabelecidos no parágrafo 2° 
                  do art. 96-A da Lei n° 8.112/1990, bem como o que dispõe os arts. 27, 39 e 51 do Anexo IV do 
                  Regulamento Administrativo do Senado Federal (consolidado pela Resolução do Senado 
                  Federal n° 13/2018)." "modalidade ônus limitado, conforme dispõe o caput do art. 35 do Anexo IV do RASF,  sendo 
                  devido apenas as parcelas remuneratórias ordinárias relativas a seu cargo e nível de carreira, 
                  como pode ser observado na transcrição do art. 29 do Anexo IV do RASF colacionado abaixo: 
                            Art. 29. As modalidades de participação do Senado Federal no apoio 
                            financeiro à participação de servidores em ações externas de capacitação são 
                            as seguintes:  I - com ônus total, sendo devido o pagamento de todas as parcelas previstas 
                            no § 2- deste artigo. 
                            II - com ônus limitado, sendo devido o pagamento das parcelas previstas 
                            nos incisos I e II do § 2º deste artigo. 
                            § 2 - O servidor participante de ações externas de capacitação que impliquem 
                            ônus poderá receber as seguintes parcelas: 
                              I - todas as parcelas remuneratórias ordinárias relativas a seu cargo e 
                            nível na carreira; Art. 35. A concessão de afastamento de servidor do Senado Federal para 
                            participar de programas de pós-graduação, stricto sensu, ocorrerá na 
                            modalidade ônus limitado, sendo devido o pagamento apenas da parcela 
                            prevista no inciso I do §2º do art. 29 deste Anexo, 
                  Assim, em vista das manifestações esposadas nos autos, não se vislumbra 
                  qualquer óbice ao deferimento do pleito, <<**especialmente considerando que a qualificação e/ou 
                  atualização de conhecimentos do corpo técnico da Casa é condição indispensável para a 
                  profícua atuação profissional em seus respectivos âmbitos de atuação. 
                  Registre-se, ainda, que o pedido se coaduna com diretrizes da Carta de 
                  Compromissos do Senado Federal, mais especificamente com o pertinente à excelência na 
                  prestação de serviços públicos, sendo que a todos devem ser proporcionadas formação adequada e capacitação continuada para o bom exercício de suas funções, razão por que 
                  opinamos pelo deferimento, nos termos aqui apresentados." 
639 - 643  se vê: Data de autuação: 18/3/2020, publicação em 06/04/2021. Um ano e um mês depois. 
                  "decisão foi publicada no BASF nº 7778, de 6/4/2021, concede afastamento ao servidor THIAGO CORTEZ 
                  COSTA, matrícula nº 226674, no período de 24 de outubro de 2020 a 16 de agosto 
                  de 2024, para participar do programa de Pós-Graduação Strictu Senso – Doutorado"
644 -645 - email do SEPOS: citando art. 49, §3°,4°, 5°e 6° 
e também cita L8112, art. 96-A. De qualquer forma, art. 49 não é sobre afastamento, é sobre licença. 
 
657 - de novo oficio cita art. 49: 
                  “§ 3º A não apresentação de documentação comprobatória ou sua apresentação em 
                  desacordo com o deferimento ensejará a cassação da licença. (Incluído pelo Ato da Comissão Diretora nº 11/2021)  
                  § 4º O servidor que, injustificadamente, não apresentar a documentação referida no 
                  caput deste artigo poderá ser submetido à apuração de responsabilidade na esfera 
                  administrativa, nos termos do art. 138 deste Regulamento Administrativo. (Incluído pelo Ato da Comissão Diretora nº 11/2021) 
                  § 5º A cassação da licença para capacitação implicará a perda do direito de gozo da 
                  licença e da remuneração correspondente ao período cassado. (Incluído pelo Ato da Comissão 
                                                                               Diretora nº 11/2021) 
                  § 6º A ausência de comprovação de atividade formal de capacitação durante o 
                  período autorizado para afastamento ensejará a cassação integral do período não 
                  comprovado. (Incluído pelo Ato da Comissão Diretora nº 11/2021).”
662 - de novo oficio cita art. 49... 

669 - 682 arquivos dos relatórios cobrados nos ofícios são ocultados do processo (algum outro tipo de arquivo?)

683 -  00100.100844/2023-26 relatório, visível

741 - mais um relatório, visível 00100.100844/2023-26-1 (ANEXO: 001)
00100.025718/2023-8

933 - mais um relatório, visível  00100.100844/2023-26-2 - ver data 08/06/2023 -> demonstra regularidade da comunicação com o SEPOS. Não podem alegar que estava ausente e sem prestar informações.

990-995 - páginas ocultadas

996 - 00100.156021/2023-55       primeiro ofício que cita os artigos corretos relativos a afastamento: Lembramos que a apresentação das informações solicitadas pelo ILB está delimitada 
                  pelas normas vigentes, notadamente o artigo 41 do Anexo IV do RASF (Ato da Comissão 
                                                                                      Diretora n° 14/2022): 
                    “Art. 41. São deveres do servidor, durante o período de afastamento:  
                    I  –  Enviar  ao Instituto Legislativo Brasileiro o relatório de atividades  
                  acadêmicas, incluindo eventual produção acadêmica já realizada; II - enviar ao Instituto Legislativo Brasileiro o comprovante de 
                  frequência no curso, quando solicitado;  
                  III  – prestar outras informações a respeito de suas atividades 
                  acadêmicas que forem solicitadas pelo ao Instituto Legislativo 
                  Brasileiro.”
                  
OBS: Em 2022, um Ato da Comissão Diretora consolidou alterações feitas ao longo do tempo, desde a Resolução 13/2018. É discutível se esse novo ATC 14/2022 passa a ser a norma de regência do caso do servidor: primeiro porque a relação de afastamento se iniciou na vigência da norma anterior e segundo, porque a Resolução 13/2018 é norma de patamar superior ao ATC 14/2022. Pelo artigo 97 (se não me engano) do Regimento Interno do Senado Federal, a Comissao Diretora tem prerrogativa de propor projeto do regulamento administrativo do Senado Federal, na forma de projeto de Resolução, mas é o plenário que decide se aprova ou não. A rigor, portanto, o ATC 14/2022 não seria auto-executável e precisaria ser referendado pelo plenário para ter vigência válida. Isso só ocorreu em 2024, bastante tempo após os fatos, portanto. o fato é que com as alterações promovidas pelo ATC 14/2022, o art. 40 da Res 13/2018 virou art. 41. 

1035 a 1043 - 05/10/2023 relatório de atividades de 1o. de 2023. Esse tem informações sobre as atividades acadêmicas realizadas pelo servidor no período, mas também informa sobre problemas de saúde, apresenta atestado e relatório médico e informa sobre o trancamento do semestre solicitado pelo servidor em 18/07/2023 sobre o semestre que estava acabando. Contrasta com os relatórios ocultados sob sigilo o fato de este relatório contendo informações médicas do servidor ter ficado à mostra, acessível publicamente, mesmo sob pedidos do servidor de preservação de sua intimidade exposta nas informações de saúde. Esse relatório com informações sensíveis continua aberto, a despeito do sigilo que colocaram em outros inexplicadamente.
                  
1044 a 1294 - páginas ocultadas sob sigilo - justamente as páginas dos relatórios repetidos que o SEPOS incluiu e ele próprio ocultou depois. o processo atingiu o objetivo, com encaminhamento da acusação sobre mim alegando ausência de atividades acadêmicas e atrasos no envio dos relatórios (os relatórios ocultados sob sigilo, junto das atividades acadêmicas que eles relatam). não foi aberta apuração acerca do que eu denunciei sobre o chefe do SEPOS, e sua atuação para me denegrir.

1295 a 1301 relatório do SEPOS sobre o 1º semestre de 2023, omitiu as informações sobre minhas atividades acadêmicas seletivamente para dar ênfase na enfermidade e consequente trancamento.
       
>       Observe-se que ele não encaminha denúncia, nem representação formal contra mim. Não há indicação de fato, ato ou omissão com o qual eu tenha infringido alguma regra, nem há indicação de qual foi essa regra e como ela foi infingida por minha conduta. O ILB encaminha meu caso para apuração e deliberação superior com base num possível dano ao objetivo do afastamento: "potencial impacto no cumprimento do objeto que ensejou o ato autorizativo [do afastamento]". 
       
>       Há que se diferenciar aqui o tipo de encaminhamento à apuração de responsabilidade feito pelo ILB e o de alguém que, sendo leigo, não tem conhecimento suficiente para distinguir entre fato estranhado e ilicitude. A legislação do processo administrativo e a constituição estabelecem que: 1) pelo princípio da legalidade, haja previsão legal específica dos fatos cuja responsabilidade deva ser verificada - como os demais atos da Administração, a responsabilização também requerem previsão legal; e 2) pelos princípios da publicidade e da transparência, que tais atos explicitem os seus fundamentos legais. 
       
>       Adota-se certa permissividade, em relação às formalidades necessárias, quando um leigo representa contra possível irregularidade em campo que foge de sua competência, ou quando o denunciante não detém acesso a todas as informações que seriam necessárias. A apuração, nesses casos, será para obtenção de informações em fontes complementares, alternativas e primárias. A imprecisão inicial era compreensível em vista das lacunas de conhecimento e informação. Tamanha frouxidão, contudo, não deve ser estendida a servidores remunerados especificamente com atribuição de fiscalizar o cumprimento das normas. Trata-se de rotina de trabalho em atividade técnica na área de especialização do servidor e do órgão em que atua. 

 >      O ILB é órgão grande e bem estruturado responsável pela capacitação de servidores do Senado, e o SEPOS (ou a COESUP) é serviço composto por 12 indivíduos (fora estagiários e terceirizados) com atribuição específica para fiscalização de atividades de servidores em pós-graduação. Em outras palavras, é responsável por acompanhar o "cumprimento do objeto de seu afastamento para participação em programa de pós-graduação stricto sensu no país" (00100.009313/2024-81 (pagina 03), também 00200.003561/2020-66 (pagina 1304).
       
>       Quando um órgão é responsável técnico por verificar o cumprimento das normas e, em ato de ofício, dá início a acusação contra servidor, então há obrigação legal de especificar o fato e a norma que originam a acusação. O encaminhamento sem a devida fundamentação é inadmissível. Ele indica a falta de norma prévia que tipifique a conduta, ou a falta de uma conduta tipificável. Em nenhum desses casos há fundamento para dar continuidade à apuração e o procedimento é encerrado. 
       
>       Em suas atividades de instruir processos e de monitorar o cumprimento das normas relativas à capacitação, não é admissível que o ILB engatilhe procedimento de apuração contra servidor em pós-graduação baseando-se em instrução processual vaga e infundada. Enquanto órgão especializado, exige-se a devida explícita clareza de pressupostos jurídicos e factuais. O dever funcional e as atribuições especializadas requerem que os atos processuais do órgão sejam explícitos em relação a qual ou quais são os fatos questionados, em qual norma está tipificada a irregularidade e como logicamente os fatos violam a norma. 
>       Qualquer outra possibilidade que implique na continuidade da apuração requer a especificação do fato e da norma. Se há um ou mais fatos questionáveis, devem ser explicitamente tipificados com as correspondentes normas. Se há uma ou mais normas implicadas, devem ser citadas. A dúvida ou a divergência interpretativa não eximem o órgão técnico de apresentar suas motivações formalmente. A continuidade do procedimento de apuração sem a explícita motivação é falta funcional, ilegalidade e possivelmente crime doloso.
       
1302 a 1306 - e-mails em que questiono o encaminhamento feito pelo ILB


1307 a 1310 - despacho DGER questiona ILB: 00200.003561/2020-66 (VOLUME 1) - 00100.039283/2024-37
            - documento assinado por Ilana em 12 de março de 2024, conforme visualização no SIGAD^[ILANA TROMBKA:74270745053 em 12/03/2024 06:25:53. Veja que o documento da página seguinte, 1311, de Messias, foi assinado em 31 de janeiro de 2024, dois meses antes, mas só inserido no processo depois do de Ilana, assinado em 12 de março daquele ano.]

      Alegações: 

  p.1307

                  - Cita trancamento de matrícula pelo servidor em parte do período de afastamento, sem mencionar nenhuma                         norma que tenha sido infringida.

  p.1308

                  - Faz referência a atestado médico enviado pelo servidor e cita normativo que disciplina a submissão destes                     documentos à "Junta Médica":
> Atestado^ médico anexado pelo servidor, de 30 (trinta) dias, a partir de 07/04/2023, não submetido à Junta                     Médica do Senado Federal, nos termos do art. 4° do ATC n° 17, de 2011^[Art. 4° Após 0 atendimento médico,                     o servidor, ou alguém em seu nome, deverá apresentar o respectivo atestado á Junta Médica no prazo máximo                     de 2 (dois) dias úteis ou, caso convocado para depor em sindicância, no prazo de 1 (um) dia útil a contar                     do inicio do afastamento.]

  p. 1309


                 - Menciona relatórios de atividades encaminhados pelo servidor, atestado, requerimento de trancamento,                          deferimento pela UnB, atestado de matrícula, declaração de aluno regular.
                 - Daí, pede resposta a questionamentos e informações para embasar decisão que tomará: 
> Ante o exposto, com fulcro na competência insculpida no art. 58, parágrafo único^[Art. 58. O Instituto Legislativo Brasileiro e a unidade responsável pela gestão de pessoas do Senado Federal devem **desenvolver, conjuntamente, procedimentos de controle e registro da participação** dos servidores em ações de capacitação. Parágrafo único. Em caso de **descumprimento injustificado**, pelo servidor, dos deveres expressos nos arts. 32, 41, 42 e 52 deste Anexo, o ILB dará ciência á Diretoria-Geral, que poderá deliberar a imediata suspensão dos vencimentos do servidor a ser executada pela unidade responsável pela gestão de pessoas, sem prejuizo das medidas anteriormente previstas], do Anexo IV do RASF, a fim de embasar a deliberação da Diretoria-Geral, ENCAMINHO os autos à Vossa Senhoria para que sejam esclarecidos os seguintes pontos:(...)
                  - Verificar de quando é essa redação, i.e. de que versão do RASF.<- é do ATC 14/2022, na RES 03/2018 não havia essa redação. 
                  
                  
                  - Pergunta se houve aproveitamento de créditos em relação a alguma disciplina, sem mencionar norma relacionada à pergunta. Também não cita norma relativa à pergunta sobre grade curricular, numero de disciplinas ou de créditos, detalhamento de histórico do servidor.
                  - pergunta se o servidor cumpriu obrigações:

> dispostas nos artigos 40 e 41 do anexo IV do RASF^[Art. 40. São deveres do servidor, durante o período de afastamento: I - enviar ao Instituto Legislativo Brasileiro relatório de atividades acadêmicas, incluindo eventual produção acadêmica já realizada; II - enviar ao Instituto Legislativo Brasileiro comprovante de frequência ao curso, quando solicitado; III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro. Art. 41. São deveres do servidor, após a conclusão do curso: I - entregar, em até sessenta dias após a conclusão do programa, cópia da dissertação ou tese aprovada para a obtenção da titulação; II - executar ação de disseminação e aplicação do conhecimento adquirido na pós-graduação, quando requisitado pelo Instituto Legislativo Brasileiro, nos termos do § 8° do art. 19 deste Anexo; III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro.] 

  p.1310

                  - Além disso, fez as seguintes perguntas, sem apontar a fundamentação normativa para cada uma das exigências: pede para o ILB informar 1) os prazos definidos para a prestação de contas, em cada semestre, e 2) se os referidos prazos foram respeitados pelo servidor; 3) Caso não tenham sido respeitados, detalhar, por semestre, quanto tempo o interessado levou para prestar contas adequadamente em relação às datas estabelecidas; 4) As prestações de contas do servidor evidenciam o efetivo desempenho e o aproveitamento da capacitação realizada em cada período? Detalhar.; 5) Há alguma prestação de contas inadimplente? Detalhar.; 6) O servidor comunicou tempestivamente ao ILB ter tido deferida alguma licença para tratamento de saúde pelo Senado Federal? Detalhar.; 7) O servidor comunicou previamente ao ILB a decisão de trancamento geral de matricula? Se sim, indicar o NUP referente à deliberação de autoridade competente.
                  

p.1311 - ILB cobra relatório, e cita RASF, anexo iv art. 41, em fundamentação (ATC 14/2022) - assinado em 31/01/2024, porém inserido em março de 2024, após documento da dger contido na pagina anterior (1310).

1313 a 1324 - Páginas ocultadas sob sigilo. Provavelmente é meu relatório, que ele restringe acesso para reforçar imagem de não entrega...

1325 a 1327  - calendário que enviei junto do relatório, deixado à vista sem sigilo.

1328 a 1330 - mais páginas sob sigilo

1331 -  00200.003561/2020-66 (VOLUME 1) - 00100.054213/2024-17 e-mail em que informo greve de servidores da UnB em 20 de março de 2024

1336 -  00200.003561/2020-66 (VOLUME 1) - 00100.054278/2024-54 data de 02/04/2024, porém repete e-mail datado de 03/02/2023, cobrando relatórios já entregues há muito tempo.

        SEPOS/ILB insere novamente e-mail datado de 03/02/2023 cobrando relatórios referentes a 02/2021 e 01/2022, em que diz que nao respondi  ofícios nº 043/2022-SEPOS/COESUP/ILB, de 04/08/2022 (NUP 00100.090511/2022-09) e 070/2022-SEPOS/COESUP/ILB, de 27/10/2022 (NUP 00100.133503/2022-56),

1337 -  00200.003561/2020-66 (VOLUME 1) - 00100.058912/2024-28, envio repetido, separado do anterior, ou seja, proposital, inserindo no processo mais uma vez o email em que envio relatório de 02/2021

1339 a 1352 - ILB responde questões da DGER: 

    1340 - cita perguntas e rasf anexo IV art. 40 e 41

    1341 a  1343 - apresenta currículo / grade de disciplinas

    1348 - responde a "O servidor cumpriu com as obrigações dispostas nos arts. 40 e 41 do Anexo 
    IV do RASF14, em todos os semestres do afastamento, dentro do prazo estabelecido?" 
       
       "Quanto a "Listar os NUPs de todos relatórios de atividades por semestre fornecidos até o momento, 
       organizados em ordem cronológica crescente", a lista dos NUPs dos relatórios semestrais 
       fornecidos até o momento consta na Tabela 1, a seguir."
       
      "Quanto a "Informar os prazos definidos para a prestação de contas, em cada semestre, e se os 
      referidos prazos foram respeitados pelo servidor. i. Caso não tenham sido respeitados, detalhar, por 
      semestre, quanto tempo o interessado levou para prestar contas adequadamente em relação às datas 
      estabelecidas.”, **não há prazos definidos para a prestação de contas**, em cada semestre, **conforme 
      art. 41 do RASF**. A Tabela 1, a seguir, traz as datas de solicitação dos relatórios por parte do 
      ILB e de envio por parte do servidor, a cada período:"
      
    1349 -       **Tabela 1 – Solicitação e recebimento de relatórios de atividades por período**

| Relatório | Semestre letivo declarado | Período declarado¹⁷              | Data de solicitação do relatório pelo ILB         | Data de envio do relatório ao ILB                     |
|-----------|---------------------------|----------------------------------|----------------------------------------------------|--------------------------------------------------------|
| 1         | **2021.1**                | (31/05/2021–19/11/2021)          | 11/03/2022¹⁸                                       | 09/06/2022¹⁹                                           |
| 2         | **2021.2**                | (17/01/2022–05/05/2022)          | 04/08/2022²⁰ <br> 27/10/2022²¹                     | 14/09/2022²² <br> 13/02/2023²³ e 15/06/2023²⁴          |
| 3         | **2022.1**                | (16/05/2022–28/09/2022)          | 03/02/2023²⁵                                       | 13/02/2023²⁶ e 15/06/2023²⁷                            |
| 4         | **2022.2**                | (10/10/2022–25/02/2023)          | 25/05/2023²⁸                                       | 15/06/2023²⁹                                          |
| 5         | **2023.1**                | (27/02/2023–29/07/2023)          | 15/09/2023³⁰                                       | 06/10/2023³¹                                          |
| 6         | **2023.2**                | (31/07/2023–27/12/2023)          | 31/01/2024³² <br> 07/03/2024³³                     | 18/03/2024³⁴                                          |


Importante: ILB frisa que não é o momento ainda de aferir o aproveitamento da capacitação realizada pelo servidor "ainda está em andamento". RASF estabelece como descumprimento a não obtenção do título.

> "Sobre o questionamento emanado pela DGER: “As prestações de contas do servidor evidenciam o efetivo desempenho e o aproveitamento da capacitação realizada em cada período? Detalhar.”, **nota-se que o período de afastamento do servidor ainda está em andamento**." 

    1352 - 00200.003561/2020-66 (VOLUME 1) - 00100.054291/2024-11

>"Referente ao tópico: “Há alguma prestação de contas inadimplente? Detalhar”, note-se que as 
prestações de contas até o 2º semestre de 2023 estão nos autos. "

>  "Quanto à questão: “6. O servidor comunicou tempestivamente ao ILB ter tido deferida alguma licença 
para tratamento de saúde pelo Senado Federal? Detalhar.”, no processo não consta documento de comunicação do 
servidor ao ILB ou a outro órgão da Casa sobre licença para tratamento de saúde a ser previamente deferida 
pelo Senado Federal ou requerimento com esse propósito."

>  "Por fim, com relação à pergunta: “7. O servidor comunicou previamente ao ILB a decisão de trancamento 
geral de matrícula? Se sim, indicar o NUP referente à deliberação de autoridade competente.”, o servidor apresentou 
cópia de solicitação de trancamento geral da matrícula à UnB datado de 19/07/202349. O trancamento foi 
informado ao ILB por meio do Relatório de Atividades Acadêmicas referente ao 1º semestre de 2023 em 
06/10/202350."

> " Ante o exposto, sugerimos encaminhamento à Diretoria-Geral para análise e deliberação. "

------------------------ABAIXO, PÁGINA A PÁGINA ASPECTOS DO DESPACHO DA DGER, COM COMENTÁRIOS MEUS------------------

1353 a 1356  - DGER resume aspectos do relatório enviado pelo ILB e abre prazo para manifestação prévia do servidor 
             00200.003561/2020-66 (VOLUME 1) - 00100.084908/2024-15
             
             
             - somente o semestre 2023.1, compreendido entre 27/02/2023 a 29/07/2023 (período declarado), não apresenta                   conclusão com êxito de atividades letivas no doutorado
             - no processo não consta documento de comunicação do servidor ao ILB ou a outro órgão da Casa sobre licença para             tratamento de saúde a ser previamente deferida pelo Senado Federal ou requerimento com esse propósito. 
             -  O servidor comunicou previamente ao ILB a decisão de trancamento geral de matrícula? Se sim, indicar o NUP                referente à deliberação de autoridade competente.'', o servidor apresentou cópia de solicitação de trancamento                geral da matrícula à UnB datado de 19/07/2023. O trancamento foi informado ao ILB por meio do Relatório de                    Atividades Acadêmicas referente ao 1“ semestre de 2023 em 06/10/2023. (Grifos nossos e no original)
 
            p. 1354: ESSENCIAL: DGER comenta afirmação de que afastamento ainda está em curso, feita pelo ILB. Busca                      esclarecer que não se trata da avaliação final do efetivo aproveitamento da ação de capacitação, a qual se dará ao             final do afastamento, conforme afirma e faz referência ao **art. 42 do anexo iv** do rasf^[Art. 42. São deveres do servidor, após a conclusão do curso: I - entregar, em até sessenta dias após a conclusão do programa, cópia da dissertação ou tese aprovada para a obtenção da titulação; II - executar ação de disseminação e aplicação do conhecimento adquirido na pós-graduação, quando requisitado pelo Instituto Legislativo Brasileiro, nos termos do § 8° do art. 19 deste Anexo; III - prestar outras informações a respeito de suas atividades acadêmicas que forem sohcitadas pelo Instituto Legislativo Brasileiro.].
             
>  Por oportuno, é mister registrar que **não se trata de avaliação final do efetivo aproveitamento da ação de capacitação** para a qual o afastamento foi deferido, **posto que a ação ainda está em andamento e dentro do prazo máximo autorizado**. **Referida avaliação final se dará ao término do prazo do afastamento concedido, conforme definido no art. 42**^ do Anexo IV do Regulamento Administrativo do Senado Federal (RASF).

> No entanto, conforme relatado^ nos autos pelo ILB, durante o acompanhamento do afastamento, nos termos do art. 41^ do Anexo IV do RASF, verificou-se que o servidor não desempenhou quaisquer ações de capacitação com aproveitamento durante 1° semestre do ano de 2023.

p.1354     

           A DGER reconhece na página 1354 que não é cabível julgamento de eficácia do servidor na ação de capacitação, pois doutorado ainda está em curso e dentro do prazo autorizado. Tal avaliação se dará ao término do curso ou do afastamento, conforme dispositivo citado do RASF, o art. 42 do anexo IV. 

> Dito isso, tenta justificar motivação de seu intuito precipitado de avaliação de aproveitamento. Assim, faz alusão a normativo: 'nos termos do art. 41 do anexo iv do RASF' e acusa que o servidor não desempenhou quaisquer ação de capacitação 'com aproveitamento' durante o 1º semestre de 2023. Junto do peso da Instituição Senado Federal, a mera menção de dispositivo normativo parece não só credenciar a DGER para dar seguimento à averiguação de aproveitamento como também parece legitimar a própria exigência de aproveitamento aferida semestre a semestre. Também reclama que o servidor comunicou o trancamento somente em 06/10/2023 e após notificação para envio de relatório de atividades acadêmicas do primeiro semestre. (ver registros de contatos telefônicos e histórico de mensagens para o SEPOS)
           
             No entanto, a realidade requer cautela e leitura atenta. Em primeiro lugar, após afirmar que não se trata da avaliação ao término do curso (art. 42), a DGER menciona o art. 41 para basear a continuidade da acusação em que afirma que não houve nenhuma ação de capacitação com aproveitamento feita pelo servidor no período questionado. 
             Todavia, o art. 41 não exige isso! O artigo 41 estabelece como obrigação do servidor durante o afastamento o envio de "relatório de atividades", a apresentação de "comprovante de frequência, quando solicitado", e de "outras informações, quando solicitado". Não há requisito denominado de "aproveitamento"!!  Note-se que, a despeito das reiteradas alegações referentes ao caso do servidor sobre ausência de atividades acadêmicas **com aproveitamento** feitas pela DGER, a palavra 'aproveitamento' só ocorre 3 vezes em todo o Regulamento Administrativo do Senado Federal - e nenhuma delas se refere à avaliação de resultados de afastamento de servidor. Nenhuma!
             A palavra 'aproveitamento' não existe no capítulo V, que trata de afastamentos, para que seja exigido 'desempenho com aproveitamento'. Também não há previsão regulamentar de avaliação semestral. Por fim, quanto à data da comunicação, não há prazo, conforme o próprio ILB admitiu!!
             A avaliação de resultados de um afastamento de servidor em pós-graduaçao stricto sensu está prevista no art. 42, e é uma avaliação binária que ocorre ao término do curso: obteve ou não obteve o título? Uma pós-graduação é empreitada complexa, especializada demais e diversa por natureza. Difícil criar um ambiente apropriado para avaliá-la detalhadamente num contexto interno de um órgão burocrático cuja finalidade não é o ensino e a pesquisa.
             Diante da reserva do ILB em fazer julgamento do aproveitamento, a DGER admite o descabimento da avaliação de eficácia na participação de servidor.  
             
             
* TRECHO DE TEXTO INTERPRETATIVO-ARGUMENTATIVO!!             Aquele semestre 1º de 2023 representou sim um dano, mas um dano justificado: o servidor não obteve aprovação nas disciplinas, mas isso se deve a dificuldades originadas na enfermidade do servidor, as quais atrapalharam o resultado do semestre. Após analisar a documentação médica sobre a internação hospitalar do doutorando, a Universidade reconheceu que se tratava de motivo de força maior e excepcionalidade com gravidade suficiente para não registrar aquelas menções no histórico do aluno e desse modo invalidar as sanções acadêmicas que seriam impostas. Além disso, Não é verdade a afirmação de que o servidor não desempenhou quaisquer ação de capacitação com aproveitamento naquele semestre. O servidor apresentou exaustivas informações em relatório das atividades realizadas e também no processo, comprovou frequência às aulas e a participação nas atividades letivas do período questionado - inclusive comprovou a entrega de trabalhos para avaliação pelos professores. Não houve interrupção de atividades, nem omissão. 
             A princípio, a DGER demandava que o servidor se manifestasse sobre a ausência de atividades acadêmicas no semestre. Após verificar a exaustiva prova documental da atuação acadêmica do servidor, a DGER mudou de foco e se apegou, então, à questão das atividades com aproveitamento. Seria possível debater se houve ou não aproveitamento. Mas antes disso, importa notar que o normativo mencionado no texto da DGER nao conceitua 'aproveitamento', não determina qualquer obrigatoriedade de aproveitamento, não estabelece método para aferir nem critério para o distinguir do não-'aproveitamento'. 
             Na verdade, essa palavra sequer aparece no artigo 41 do anexo IV do RASF. Nas 137 páginas da publicação digital do Regulamento Administrativo do Senado Federal, 'aproveitamento' so aparece 3 vezes: 1) uma vez no artigo 161, que estabelece as matérias administrativas a serem publicadas no Diário Oficial (dentre elas, atos de provimento ou vacância de cargo público por 'aproveitamento' de servidor); 2) outra vez no art. 18 do anexo IV, que trata sobre a exclusividade do ILB na emissão de diplomas de *capacitação interna*; e 3) por fim, uma vez no art. 52 do anexo IV, em capítulo que trata de licenças com duração até 3 meses, para ações de capacitação de menor duração, cursos livres, modulares, e independentes entre si.    
              O capítulo V^[arts. 35 a 45 do anexo IV do RASF] disciplina os afastamentos de servidores para capacitação especificamente em cursos de mestrado, doutorado e pós-doutorado. Ou seja, dos dez artigos pertinentes especificamente ao caso do servidor, nenhum faz qualquer menção a 'aproveitamento', nem 'acompanhamento', 'avaliação', 'aferição', 'verificação', 'periódica', 'seriada', ou 'semestral', enfim, não há nenhuma norma nesse sentido e que trate da participação de servidores em pós-graduação. Há motivos para isso: primeiro, a avaliação de discentes em pós-graduação é atividade didática circunscrita ao âmbito da autonomia universitária - o limite é estabelecido na constituição (art.207); em segundo lugar, a política de capacitação do SF, conforme estabelecida no anexo iv (art. 3º, do anexo IV do RASF), norteia-se por princípios como o da economicidade e da indisponibilidade do interesse público. A conformidade a esses princípios torna incompatível que se replique na estrutura interna do Senado uma atividade de altíssima especialização, como é o caso de avaliações do ensino em nível de pós-graduação, na variedade de áreas de formação necessárias. Além de pouco econômica e ineficiente, há sobreposição e redundância em relação a avaliações de aproveitamento às quais os servidores discentes já são rotineiramente submetidos como parte das atividades avaliativas do aprendizado nas próprias universidades. Em terceiro lugar, a opção alternativa, isto é, a avaliação economicamente feita por reduzida equipe interna de servidores resultaria em critérios, procedimentos e julgamentos inadequados para cobrir a multiplicidade de campos do conhecimento envolvidos - em claro conflito com princípio da indisponibilidade do interesse público. Em quarto lugar, a sujeição de servidores pós-graduandos a avaliações por colegas sem a mesma formação e especialização temática, dá margem à migração de conflitos entre ensino e trabalho, e ocasião para persecuções, confundindo-se divergências no livre-pensar (e eventualmente orientações teóricas, posições ideológicas e até político-partidárias) com atritos do ambiente de trabalho. O ambiente acadêmico requer uma liberdade de expressão e pensamento crítico que o ambiente de trabalho não pode proporcionar.
           Em resumo, as reclamações da DGER quanto à averiguação de aproveitamento semestral em curso de pós-graduação stricto sensu  de doutorado, com duração prevista de 48 meses ou mais, tratam essa formação avançada como se fosse uma sequência de licenças capacitações fracionáveis em módulos independentes. Configuram-se em arbitrariedade inconstitucional porque: 1) invadem competência didática e administrativa das Universidades; 2) não há determinação prévia legal para a obrigação de demonstrar aproveitamento semestral de atividades acadêmicas e, desse modo, não há exegibilidade que se imponha ao servidor, tampouco há infração que ele haja cometido nesse sentido ou penalidade que lhe seja aplicável - ninguém será obrigado a fazer ou impedido de fazer senão por força de lei previamente existente; 3) a Diretoria Geral do Senado não tem competência legislativa primária, e a criação de normas que impliquem em restrição de direitos ou ampliação de deveres não é matéria delegável; 4) não havendo lei, as exigências feitas ferem os princípios constitucionais da legalidade, da reserva legal, da anterioridade da lei, da segurança jurídica.
             
             A aplicação que a DGER quer dar ao termo 'aproveitamento' pretende equipará-lo em sentido estrito a 'obter aprovação em disciplinas com acúmulo de créditos'. Poderíamos elencar aqui inúmeras razões pelas quais tal denotação é equivocada: o aproveitamento da pós-graduação não está restrito a carga horária em sala de aula; o foco na verdade está no desenvolvimento das capacidades para pesquisa autônoma e produção de conhecimentos; é possível obter aprovação numa disciplina e não se aproveitar nada dela; é possível reprovar, e ainda assim aproveitar alguma coisa. A imprecisão do termo não autoriza o uso de seu sentido mais estrito, é justamente o oposto - em se tratando de direitos e deveres, a imprecisão requer a aplicação do sentido menos restritivo.  'Aprovação' e 'aproveitamento' não são sinônimos: aprovar tem origem no latim, *'ad probbare'*, e denota testar, validar, corroborar; aproveitar tem raiz em *'provectus'* (proveito, vantagem, fruto), que é o particípio passado de 'proficere' (progredir), verbo formado por 'pro' (à frente, rumo, a fim de) e 'facere' (fazer), denotando futuro e fazer, ou seja ter ou dar utilidade para algo. A imposição do sentido restritivo do termo ao meu caso também revela a falta de isonomia da Administração: se servidores são afastados com a única obrigação de redigir a tese ou a dissertação, não faz sentido a DGER exigir especificamente de mim o cumprimento semestral de carga horária em sala de aula 'com aproveitamento' - mesmo eu já tendo obtido todos os créditos necessários. 
             Eu poderia continuar indefinidamente adicionando argumentos para demonstrar a improcedência do intuito e impertinência da DGER em sua exigência de 'desempenho de ações de capacitação com aproveitamento durante o 1º semestre de 2023'. Mas faltam às ações da DGER nesse caso até mesmo os fundamentos mínimos necessários. 
             O peso da instituição Senado Federal tem favorecido a ação ilegal de certos agentes à sombra da presunção de legalidade dos atos burocráticos. A realidade mostra-se bastante diversa do presumido: requer leitura atenta e desconfiada. 
             O discurso de zelo camufla violações de normas internas, de leis e até da Constituição. 
             A palavra 'aproveitamento' sequer aparece no capítulo V do anexo IV do RASF, que trata sobre o caso do servidor, isto é, dos afastamentos para cursar pós-graduação stricto sensu no país. 
             Não é verdade a afirmação. O servidor apresentou as atividades realizadas em relatório de atividades e também no  processo, apresentou comprovação de frequência às aulas e de participação nas atividades letivas do semestre questionado, inclusive comprovou a entrega de trabalhos para avaliação pelos professores. Não houve interrupção de suas atividades nem omissão.
             
             
             
P.1355 -  DGER CITA NORMAS DE FORMA MALICIOSA PARA TENTAR ENQUADRAR AÇÕES DO SERVIDOR            
00200.003561/2020-66 (VOLUME 1) - 00100.084908/2024-15
             
             1ª estratégia da DGER - 
             utiliza art. 58 do anexo iv do RASF para 'comutar' tipificação e pena entre os casos previstos nos artigos 32, 41, 42 e 52.
             
             - O RASF é determinado por Resoluçao aprovada no Plenário (que tem competência primária estabelecida pelo Regimento Interno, art. 98, inciso III)^[https://adm.senado.gov.br/normas/ui/pub/normaConsultada?16&idNorma=288972#:~:text=ao%20seu%20exame.-,Art.%2098.,-%C3%80%20Comiss%C3%A3o%20Diretora]. A Comissão Diretora tem competência para propor o projeto de Resolução (competencia também no RI, art. 98, inciso III)^[https://adm.senado.gov.br/normas/ui/pub/normaConsultada?16&idNorma=288972#:~:text=ao%20seu%20exame.-,Art.%2098.,-%C3%80%20Comiss%C3%A3o%20Diretora]. 
             
             - A esse respeito, as várias versões do RASF têm vindo com a seguinte abertura:
                          
                          Art. 1º Este Regulamento dispõe sobre as normas complementares ao regime jurídico dos servidores do
                          Senado Federal; estabelece a estrutura organizacional; fixa a competência das unidades que a
                          integram; define o número, as atribuições e as alçadas decisórias relativas aos titulares dos cargos
                          em comissão e das funções comissionadas; descreve as atribuições dos cargos efetivos; e disciplina
                          aspectos do funcionamento do Senado Federal.
                          
                          **§ 1º Em caso de necessidade, a Comissão Diretora poderá dispor sobre as matérias disciplinadas no
                          art. 52, inciso XIII, da Constituição da República, devendo submeter, em até 120 (cento e vinte)
                          dias, projeto de resolução para a deliberação do Plenário.**
                          
                          § 2º Os Atos da Comissão Diretora editados em data anterior à publicação desta resolução e ainda não
                          ratificados continuarão em vigor até que resolução ulterior os revogue explicitamente ou até
                          deliberação do Plenário do Senado Federal. (RES 13/2018, ATC 14/2022, RES 6/2024, etc.)
             
             - Dúvidas: A condição para validade das edições da Com.Dir. ao RASF é o envio do projeto de resolução em 120
             dias? Seria uma espécie de medida provisória? Vencido o prazo e nao apresentado o projeto, as edições perdem a
             validade? Se apresentado e não aprovado, o que acontece? Fato é que a RES 6/2024 que 
             
             - Na prática, e nessa ordem, a DGER, o Presidente e a Comissão Diretora têm feito alterações gerais ou pontuais, que são consolidadas depois em ato de igual patamar, mas que a rigor precisam ser referendadas pelo Plenário quando o texto compilado ganha status de Resolução e realmente ter validade no ordenamento jurídico. O problema é que muitas vezes, sobretudo agentes da administração, editam as normas infralegais à sua vontade, inclusive alterando, atribuindo vigência  e "regulamentando" os atos superiores, até onde pude verificar sem que haja competência para isso. Às vezes, o que há é uma delegação genérica com 'super poderes' ao final do texto, mas até onde entendo o ato de delegação precisa ser específico e com objeto delimitado, validade e sempre que praticado deve ser mencionada a competência por delegação. A DGER tem navegado nesse vácuo, editando atos normativos, estabelecendo 'obrigações' de fazer e dando palavra de cumpra-se - com considerável frouxidão nas partes introdutórias de normas e atos, onde "considerando os" fatos prementes ou as normas vigentes, se dá fundamento para o texto a ser publicado. A conferência mais detalhada desses pressupostos legais de competência e motivação tem frequentemente demonstrado relações desconexas entre a ação pretendida no ato e a motivação factual e legal/jurídica alegada. Por exemplo, encontrei processo que pode resultar em exoneração de servidor cujo fundamento para a iniciativa da DGER no caso era uma delegação assinada em 2015, sem objeto explícito ou sem data de validade 
             
             - IMPLICAÇÕES: 
             

             - Art. 58 é abusivo e contrário à Constituiçao. Não há possibilidade de penalidade imediata, pois a Administração não pode tomar decisão que implique na restrição de direitos nem em prejuízo de administrados sem possibilitar que as partes interessadas se manifestem. Além disso, ainda que válido o art. 58, não se permite a 'comutação' de obrigações, porque o simples fato de serem citados juntos não faz com que as regras estabelecidas no art. 52 (licença para capacitação) sejam exigidas dos casos regidos pelos arts. 41 e 42 (afastamento para pós-graduação) ou pelo art. 32 (capacitação em treinamento interno?)    
             
             - A Resolução que referendou/"ratificou" o ATC 14/2022 é a RES 6/2024, publicada em de 21/05/2024 - posterior tanto ao início do afastamento quanto aos fatos. Note-se que em 2024, a RES 6/2024^[https://adm.senado.gov.br/normas/ui/pub/normaConsultada?12&idNorma=14383035#:~:text=Download-,Normas%20Relacionadas,-Ratifica] foi editada para dar validade a alterações promovidas até 2024, inclusive a própria ATC 14/2022.
             
             - Se está correto o meu raciocínio, então a norma vigente sobre meu caso é ainda a RES 13/2018, devido à 
             ulterioridade. 
             - Se for à época do pedido ou da concessão do afastamento, então a referência é a Resolução 13/2018. Nela não 
             havia esse artigo 58 - era outra redação.
             
             - o art. 58 cita penalidade de suspensao imediata do pagamento de salário por determinação da DGER quando é 
             constatada violação dos artigos 32, 41, 42 e 52. O artigo 58 está em disposições gerais e portanto abarca todos
             os tipos de licença ou afastamento. Mas a DGER utiliza o art. 58 para tentar 'comutar' as regras do artigo 52
             para o caso do servidor, que é regido pelos artigos 41 e 42. 
             
             A exigência de aproveitamento está no artigo 52 que é específico de licenças capacitação. O primeiro artigo do capítulo não deixa dúvidas, trata das licenças adquiridas a cada 5 anos e com no máximo 3 meses de duração. Estas licenças têm origem no art. 87 da Lei nº 8112/1990.
             
             Tanto o art. 41 quanto o art. 42 do anexo iv do RASF referem-se aos afastamentos para cursos de pós-graduação, os quais têm origem nos artigos 95 e 96-A da Lei 8.112/1990.  
             
    A conclusão do despacho:  
      
> Diante do exposto, nos termos da competência estabelecida no art. 58^[Art. 58. O Instituto Legislativo Brasileiro e a unidade responsável pela gestão de pessoas do Senado Federal devem desenvolver, conjuntamente, procedimentos de controle e registro da participação dos servidores em ações de capacitação. Parágrafo único. Em caso de descumprimento injustificado, pelo servidor, dos deveres expressos nos arts. 32, 41, 42 e 52 deste Anexo, o ILB dará ciência á Diretoria-Geral, que poderá deliberar a imediata suspensão dos vencimentos do servidor a ser executada pela unidade responsável pela gestão de pessoas, sem prejuizo das medidas anteriormente previstas.] do Anexo IV do Regulamento Administrativo do Senado Federal (RASF) e considerado o disposto no art. 132^[Art. 132. São competentes para conceder licenças aos servidores do Senado, após verificação do preenchimento dos requisitos legais e regulamentares: I-0 Presidente, nos casos de quaisquer licenças no exterior; II-0 Diretor-Geral, nos demais casos. (...) § 2° Ato do Diretor-Geral regulamentará os procedimentos e prazos relativos ás licenças previstas em lei.] do RASF, nos arts. 42, inciso III^[Art. 42. (...) 111 - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro.] e 43 inciso V^[ Art. 43. O Diretor-Geral determinará o ressarcimento ao Senado Federal, do valor correspondente ao incentivo concedido, do servidor que: (...) V - não cumprir os deveres impostos no art. 42 deste Anexo.] do Anexo IV do mesmo Regulamento e no Ato da Diretoria-Geral (ADG) n° 26/2017^*^, ENCAMINHO os autos a Vossa Senhoria para que notifique o servidor THIAGO CORTEZ COSTA, matrícula n° 226674, para manifestação prévia quanto à ausência de atividades acadêmicas no 1“
             
             
             - mais uma citação deslocada, sem pertinência e sem propósito: a do art. 132 do RASF, dizendo que o DGER é competente para conceder licenças e que ato da DGER regulamentará procedimentos e prazos de licenças. O caso do servidor é de afastamento, tratado no art. 134: "§ 2º O afastamento para capacitação do servidor será concedido conforme o disposto no Anexo IV deste Regulamento." (art. 134, § 2º do RASF, ATC 14/2022 | art. 132, § 2º do RASF, RES 13/2018). Diante dessa citação, a pergunta é: por que a DGER enviou o processo para obter autorização do presidente se ela tinha competência para autorizar o afastamento? E se ato da DGER iria regulamentar (ainda mais?) procedimentos e prazos, então qual seria o ato da DGER, já publicado, que o servidor teria infringido?
             - AQUI A MALÍCIA: O texto da DGER invoca os arts. 42, inciso III, e 43, inciso V, do anexo IV do RASF. O primeiro dispositivo estabelece uma obrigação, o segundo uma penalidade. O inciso III do art. 42 diz: "São deveres do servidor, após a conclusão do curso: (...) III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro". O inciso III do art. 41, não citado, diz: "São deveres do servidor, durante o período de afastamento: (...) III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro". Um fato que se destaca é que o artigo 41 tem exatamente a mesma redação do artigo 42 em relação ao inciso III. Por que motivo então a DGER utiliza o 42? Porque para o artigo 42 há penalidade prevista no 43, mas para o 41 não há. Aí, porém, reside a contradição: no começo do documento, a DGER afirmava que: 
>             **não se trata de avaliação final do efetivo aproveitamento da ação de capacitação** para a qual o afastamento foi deferido, **posto que a ação ainda está em andamento e dentro do prazo máximo autorizado**. **Referida avaliação final se dará ao término do prazo do afastamento concedido, conforme definido no art. 42**^ do Anexo IV do Regulamento Administrativo do Senado Federal (RASF).

Ao dar seguimento à apuração de responsabilidade e determinar prazo para manifestação prévia do servidor, a DGER privilegia o artigo 42, inciso III, alegando assim que o servidor deixou de prestar informações ao ILB, em detrimento do inciso III do art. 41, que também é sobre a prestação de informações ao ILB. Há pelo menos duas diferenças entre os dois artigos: 

# A primeira diferença é do 'momento' ou fase do afastamento, o art. 41 trata de obrigações durante o afastamento e o 42 trata de obrigações ao término.

# A segunda é que o descumprimento do art. 42 tem penalidade prevista no artigo 43 (ressarcimento por não obtenção do título, por não permanência em atividade no serviço público, por não disseminar o conhecimento ou por não prestar informação ao ILB), mas para o descumprimento do 41, não há penalidade. 

Enquanto durar o curso, não estará configurada a condição para a penalidade, que é a não obtenção do título. E veja, a DGER havia afirmado parágrafos antes que não se tratava de apuração com relação ao artigo 42, por saber que o doutorado ainda estava em curso e dentro do prazo máximo autorizado! Ciente de que o servidor se encontra na situação disciplinada pelo art. 41, isto é, durante o afastamento, e que o 41 não provê penalidade, a opção da DGER por referenciar o art. 42 se deve à pretensão de penalizar o servidor, ainda que de forma reconhecidamente injusta! Aqui fica configurada a intencionalidade e o viés da direção na condução do processo.

O documento finaliza com a decisão de encaminhar os autos e notificar o servidor para "**manifestação prévia quanto à ausência de atividades acadêmicas no 1º semestre de 2023, em desacordo com os termos regulamentares do afastamento deferido e concedendo-lhe o prazo de 10 (dez) dias para manifestação, nos termos do art. 44 da Lei nº 9784/1999, em face de possível descumprimento de ação de capacitação no 1º semestre de 2023**" (NUP 00200.003561/2020, p. 1355-1356, ou NUP 0100.084908/2024).

Nota-se que, apesar de fazer referência de passagem ao ADG nº 26/2017, que "dispõe sobre os procedimentos relativos à concessão das licenças para tratamento da própria saúde", o texto não insta o servidor a que se manifeste em relação a esse aspecto nem deixa claro o dispositivo infringido no normativo, visto que não solicitou licença médica ao órgão nem à Universidade. Tendo consciência de já estar afastado do Senado, ao sair da internação hospitalar o servidor proativamente pediu à UnB que lhe fosse permitido dar continuidade aos estudos e acompanhar o conteúdo por meio da realização de exercícios domiciliares. Em face das decisões judiciais favoráveis que há acerca da não necessidade da prestação dos exercícios domiciliares para justificativa das ausências às aulas, a atitude proativa do servidor é prova de sua boa-fé genuína, de que não foi omisso e de que atuou para evitar as consequências negativas da enfermidade.  

----------------FIM DA ARGUMENTAÇÃO SOBRE DESPACHO DA DGER---------------------

p. 1357 - ILB dá encaminhamento a setor responsável por notificar o servidor


p. 1358 e 1359 - ocultadas sob sigilo

p. 1360 - e-mail comunica o servidor do prazo para manifestação (04/06/204)


À época, sem conhecer o decreto-lei que lhe concedia esse direito, a iniciativa do servidor é prova de sua boa-fé, de seu genuíno interesse e de que fez o que estava ao seu alcance para evitar as consequências daquele semestre, não contribuiu para elas. de que os resultados daquele semestre   as ausências decorrentes de sua situação de saúde fossem  evitar a sobreposição de afastamentos e pro ativamente solicitou à Universidade Acreditando que desta forma evitaria conflito entre afastamentoss ausências em virtude do tratamento de saúde  

p. 1361 a 1363 - e-mail comprovante de envio/recebimento

p. 1364 e 1365 - email com questionamentos do servidor e a resposta do Senado sobre rito processual

1) O servidor perguntou: "A norma que a DGER cita no ofício diz:  “Art. 44. Encerrada a instrução, o interessado terá o direito de manifestar-se no prazo máximo de dez dias, salvo se outro prazo for legalmente fixado” (Lei n° 9.784/1999). Já o texto do despacho da DGER diz: “Após o término do referido prazo, os autos deverão ser instruídos e restituídos à DGER para continuidade da análise.” A manifestação do ‘interessado’ ocorre após encerrar a instrução, ou ainda haverá instrução após minha manifestação?"

A resposta:
> "A manifestação do interessado ocorre após finalizada a instrução e antes de ser proferida decisão. Havendo manifestação prévia, o setor responsável pela instrução se manifesta acerca da manifestação prévia apresentada e encaminha os autos à DGER, para análise e deliberação."

2)  Na fase de instrução, o SEPOS, do ILB, inseriu em duplicidade documentos que já constavam no processo anteriormente. Relatórios acadêmicos mais recentes ficaram “soterrados” sob uma camada de 200 a 300 páginas desnecessárias e repetidas, dificultando o acesso a informações mais atuais. Do texto original, o SEPOS destacou somente trechos de sua conveniência.  Como devo proceder em relação a esses fatos? E como proceder no processo para evitar que numa eventual nova instrução haja seletividade de informações?

> "As alegações referentes às informações contidas e consideradas na instrução deverão ser arguidas na 
própria manifestação prévia, para deliberação da DGER." 

3) Inicialmente, o SEPOS e a COESUP sugeriram encaminhar “meu caso” à DGER em virtude de possível atraso/comprometimento da conclusão do meu curso. Mas quando na época apontei o prazo ainda disponível, viram que era insustentável alegar atraso ou falha em concluir o curso – então silenciaram sobre a motivação. O processo continuou tramitando sem pontuarem de forma obje va qual seria a irregularidade em meu processo a requerer manifestação da DGER. Recentemente, após intervenção da DGER, chegou-se ao suscinto ponto: “ausência de atividades acadêmicas no 1º semestre de 2023” – sobre o qual devo me manifestar. Nessa manifestação para a qual foi aberto prazo, devo me ater exclusivamente ao ponto ques onado pela DGER? Em que momento poderei me manifestar em relação à forma como o processo tem sido conduzido no ILB? 

> A alegações referentes à instrução do processo também deverão ser arguidas na própria manifestação 
prévia, para deliberação da DGER.

p. 1367 a 1420 - Manifestação prévia do servidor - 17/06/2024 - dia 14 caiu numa sexta-feira, se não me engano
ate 1476 - cópia, via processo enviado pelo SEPOS, da manifestação

             Da resposta do ILB aos pontos elencados pela DGER, a situação configura-se da seguinte forma:
             
             1. o afastamento ainda estava em andamento
             2. não havia inadimplência do servidor em relação à "prestação de contas"
             3. não havia norma que determinasse prazo para apresentar relatório de atividades parciais
             4. faltava apenas uma matéria para completar a quantidade de créditos exigida no doutorado
             5. nas disciplinas em que estava matriculado havia créditos suficientes para completar a quantidade necessária
             6. em todos os semestres o servidor obteve 'aproveitamento' e 'efetivo desempenho', exceto em 1º/2023, de acordo com o SEPOS
             7. não houve comunicado ao ILB sobre ter licença para tratamento de saúde previamente deferida pelo Senado
             8. não houve comunicado prévio ao ILB sobre o trancamento justificado de matrícula por motivo de saúde
             
             De tudo, a DGER decidiu que o servidor deveria se manifestar sobre a ausência de atividades acadêmicas no 1o semestre de 2023.
             
             O servidor apresentou as provas das atividades acadêmicas realizadas no período questionado
             
             Em análise dos artigos 41, 42 e 43 do anexo IV do BASF, servidor apontou que não havia nos normativos qualquer vedação à sua conduta, que agiu em conformidade com as regras tanto do Senado quanto da Universidade.
             
             Seguindo orientação recebida por e-mail, onde havia arguido a lisura dos envolvidos na condução do processo, trouxe a arguição para os autos tecendo críticas à forma como tem sido feito o monitoramento de suas atividades, apontando excessos administrativos, na forma de exigências reiteradas e arbitrárias na prestação de relatórios em quantidade muito maior do que previsto nas normas, apontando também a seletividade de informações negativas e a omissão completa de suas atividades acadêmicas do relatório que o ILB havia apresentado à DGER sobre suas atividades, a inserção de centenas de páginas desnecessárias ao processo (ineficiência processual) causando-lhe prejuízo claro (as páginas desnecessárias eram cópias documentos que já constavam nos autos e foram postas por cima do relatório completo em que o servidor relatava suas atividades naquele primeiro semestre de 2023: as páginas repetidas dificultaram acesso no processo às informações sobre as atividades acadêmicas do servidor no semestre. O acesso dificultado pelo ILB ao relatório do servidor com informações das atividades acadêmicas do semestre, combinado com a completa exclusão dessas mesmas informações do relatório do ILB à DGER, com claro viés seletivo em prejuízo do princípio da imparcialidade, foram condições suficientes para a DGER acreditar que o servidor não tinha realizado atividades naquele semestre e, daí, a questioná-lo exatamente sobre "ausência de atividades acadêmicas". Foi esse questionamento que fundamentou a continuidade do procedimento administrativo contra o servidor), o vazamento de dados médicos do servidor, tudo isso foi arguido pelo servidor nos autos, apontando a parcialidade dos responsáveis no ILB no monitoramento de suas atividades na pós-graduação. Foram nove itens contendo inquirições, pedidos de informação e de esclarecimentos que juntos arguiam a suspeição dos responsáveis no ILB pela condução do processo - o que o servidor já havia feito anteriormente por e-mail (p. 1365 00200.003561/2020). Mas a DGER também violou o princípio constitucional da imparcialidade, na medida em que ignorou completamente todas as vezes em que o servidor arguiu a suspeição dos servidores no ILB. Nenhuma providência foi tomada pelo Senado em relação às afirmações que o servidor teceu em relação à condução do processo, nem para contestá-las, nem para inquirir o órgão envolvido, nem para garantir o direito do servidor à resposta, à informação, à transparência, e principalmente o direito de exercer sua defesa com todos os recursos possíveis, inclusive o de demandar informações, inquirir testemunhas, ajuntar provas em sua defesa e o de contestar tudo o que é apresentado contra ele. Sem ter assegurada a ampla defesa, resta violado também o princípio do devido processo com possível desvio de finalidade e abuso de poder.   
             
             
p. 1477 a 1483    - ILB apresenta relatório da manifestação prévia do servidor

             - O ILB recebeu o processo com a manifestação do servidor em 17/06/2024
             - O prazo limite do afastamento era 16/08/2024, conforme despacho nº 684/2021-DGER publicado no BASF nº 7778, de 06/04/2021
             - O ILB reteve o processo internamente, sem se posicionar sobre a manifestação prévia do servidor por 72 dias
             - Intencionalmente ou não, o órgão permaneceu com o processo em sua carga até depois do prazo de afastamento do servidor vencer, e só então inseriu no processo suas considerações sobre argumentos e provas do servidor de que tinha de fato realizado atividades acadêmicas no semestre questionado pela DGER.
             - Não consta nos autos pedido de prazo adicional para se manifestar, nem justificativa para a demora de sua participação no processo.
             - Somente incluiu o relatório da manifestação prévia em 28/08/2024
             - Com isso, prejudicou o servidor, visto que, o relatório do ILB precedia a decisão da DGEr, e sem a decisão sobre a regularidade do semestre questionado, não sabia se iria poder prosseguir ou não seus estudos e, consequentemente, se caberia ou não solicitar ajuste nos prazos de afastamento.
             - Embora tenha reprisado os argumentos do servidor sem contestá-los ou fazer oposição a nenhum deles, o envio tardio do relatório contribuiu para a indefinição do status do afastamento e para a insegurança jurídica do servidor.
             - Assinam o despacho apenas Rainer Junio de Souza, Fabio Renato da Silva e Fernando Meneguin, sem assinatura de Messias de Queiroz, chefe do SEPOS.
             
P. 1484 a 1487 - Depois de demorar 80 dias, DGER não decide processo. Envia mais uma vez ao ILB.

             - após servidor apresentar a manifestação prévia e o ILB apresentar relatório, a DGER demora 80 dias com o processo estagnado. Não apresenta qualquer justificativa para o atraso em emitir uma decisão. Quando finalmente resolve se pronunciar, não é para decidir: incorre em omissão, por não decidir quando devia (Lei 9784/99), viola a formalidade processual devida no processo administrativo (Lei 9784/99 e Lei 8112/90), retém o processo indevidamente e sem justificativa, a qual se existisse deveria ter sido apresentada (Lei 9784/99). Quando resolve se pronunciar, não é para decidir, mas para enviar o processo mais uma vez ao ILB, sob o pretexto de que faça uma nova instrução do processo. A inversão de sentido no fluxo de tramitação processual não tem fundamentos, pois não houve fato novo com relação ao 1o semestre de 2023 para que se alterasse o que o ILB já havia analisado, tanto dos fatos que o próprio órgão trouxe ao processo quanto dos argumentos e provas que o servidor havia apresentado, e comentou quse de se omite da decisão e solicita ao ILB que faça nova instrução do processo. A intenção real da DGER tem com a inversão de sentido da tramitação se revela em trechos como:

> "que as obrigações dispostas no art. 42 do Anexo IV do Regulamento Administrativo do Senado Federal (RASF) relacionadas aos deveres do servidor após a conclusão do curso não seriam ainda exigíveis ao interessado, dado que, à época, o afastamento ainda estava em curso" p. 1485

             - A DGER expressa com os seguintes termos que as obrigações relativas "aos deveres do servidor após a conclusão do curso não seriam **ainda** exigíveis ao interessado, dado que, **à época** o afastamento ainda estava em curso". A frase sugere que, dado o atraso em decidir, agora estaria configurada situação propícia para enquadrar o servidor no artigo 42 do anexo IV do RASF e então aplicar-lhe punição. Contudo, a atitude dos dois órgãos não encontra respaldo nos estatutos e normas, pois se constitui em *venire contra factum proprium* - ato contraditório pelo qual os próprios reclamantes atuaram dando causa ao efeito que pretendem punir. A atitude dos órgãos citados em demorar a se manifestar no processo até vencer o prazo de afastamento do servidor não pode resultar em situação que o torne punível porque a própria Administração atuou para o atraso, e é ilícita a prática administrativa que induz o administrado a erro.
             
             - Não houve nenhum novo fato acerca do período em questão, o 1º semestre de 2023, que justificasse o retorno dos autos ao ILB depois que esse órgão já havia apresentado seu relatório. Se o órgão não apontou qualquer irregularidade, se não se opôs aos argumentos e provas elencados pelo servidor e, pelo contrário, os reproduziu sem questionamento ou contestação, então cabia à DGER decidir sem prolongar ainda mais o processo que já se arrastava desde outubro de 2023 sob pendência exatamente da mesma questão. O prolongamento desmotivado de procedimento administrativo é ilícito processual e configura desvio de finalidade.
             - A DGER era livre em sua decisão final, não estava obrigada a seguir a instrução processual, nem a manifestação prévia do servidor nem o relatório que precede a decisão. É livre para decidir da forma como acha correto. Tem porém o dever de apresentar justificativa fundamentada para a decisão que divergir do relatório. Quando recebe processo já instruído, com relatório do órgão responsável em que a defesa do servidor é endossada por quem antes o estava acusando, e não toma decisão pelo encerramento da matéria e arquivamento do processo, a DGER demonstra estar agindo com parcialidade e contrariamente ao servidor, com a intenção deliberada de prejudicá-lo. A despeito de todas as provas que apontam para a conformidade do servidor às normas, a atitude da DGER demonstra que não quer admitir que o servidor não cometeu falta alguma. Ao devolver o processo 80 dias depois ao ILB sem nenhuma decisão, dá provas de que não tem nenhum elemento para punir o servidor. Faltando-lhe a justificativa, a DGER encaminha o processo ao ILB, contando com sua colaboração para refazer o relatório, sem que haja sido acrescentada nenhuma informação que modificasse qualquer aspecto referente ao 1º semestre de 2023. Mas se o novo relatório apontasse para a direção pretendida, a DGER poderia somente concordar acompanhando o relatório sem ter de apresentar ela própria a justificativa. 
             - A DGER diz que o ILB restituiu os autos sem, contudo, realizar efetiva e pormenorizada análise de mérito quanto à manifestação do interessado, cita aqui o art. 58, caput e parágrafo único, que diz que "em caso de descumprimento injustificado, pelo servidor, dos deveres expressos nos arts. 32, 41, 42 e 52 deste Anexo[IV], o ILB dará ciência à Diretoria Geral, que poderá deliberar a imediata suspensão dos vencimentos do servidor (...)", e nesse parágrafo baseia encaminhamento do processo ao ILB para "manifestação conclusiva a respeito de eventual descumprimento da ação de capacitação pelo servidor quanto aos seguintes pontos (...)". Ocorre que nenhum dos pontos elencados está inscrito nos artigos 41 e 42, que se referem ao caso do servidor, que é afastamento para curso de pós-graduação stricto sensu no país, enquanto o art. 32 trata de cursos internos e o 52 trata de licença capacitação. 
             
             - Estende-se a esse despacho a discussão sobre a validade do art. 58, conforme feita acima.
             
             - A DGER cita o artigo 58, mas não aponta qual é afinal o dispositivo infringido pelo servidor. O que é que o servidor fez ou deixou de fazer?
             
             - Em seguida, DGER dá início a nova lista de itens para o ILB se manifestar. Não tendo sucesso na primeira lista que enviou, é lícito à DGER insistir na tentativa de achar falha onde não há? Após o ILB responder lista de questões em que não se achou culpa do servidor, e depois do próprio servidor se manifestar, É lícito à DGER manter o processo sem decisão? Até quando poderá tentar prejudicar o servidor?? Pode ficar reformulando indefinidamente as perguntas, sem que nenhum novo fato haja surgido, à busca de alguma versão de pergunta que produza a resposta procurada?
             

SOBRE A NOVA LISTA DE ITENS PARA MANIFESTAÇÃO DO ILB:
             - A nova lista traz assuntos nunca antes tratados, e referências normativas não citadas antes da manifestação prévia do servidor. Adicionar tais pontos a essa altura do processo requer que o servidor tenha novo espaço para manifestação em sua defesa, para exercer o contraditório. Dentre as novidades está o art. 4º do ATC 17/2011, nunca antes citado no processo:
             
> "Art. 4º. Após o atendimento médico, o servidor, ou alguém em seu nome, deverá apresentar o respectivo atestado à Junta Médica no prazo máximo de 2 (dois) dias úteis ou, caso convocado para depor em sindicância, no prazo de 1 (um) dia útil a contar do início do afastamento". art. 4º do ATC 17/2011

> Ante o exposto, com fulcro na competência insculpida no art. 58, parágrafo único, do Anexo IV do RASF, a fim de embasar a deliberação da Diretoria-Geral, ENCAMINHO os autos à Vossa Senhoria para manifestação conclusiva a respeito de **eventual descumprimento da ação de capacitação** pelo servidor THIAGO CORTEZ COSTA, matrícula nº 226674, no prazo de 5 (cinco) dias úteis, quanto aos seguintes pontos: 
1. O servidor, tempestivamente e tão logo tenha sido expedido, nos termos do art. 4º do Ato da Comissão Diretora nº 17, de 2011, apresentou o atestado médico ao Senado Federal alusivo à sua condição de saúde, conforme documento indicado no NUP 00100.177092/2023-91? 
2. O servidor apresentou, prévia e formalmente, requerimento contendo **pedido de suspensão ou de interrupção** da ação de capacitação objeto do afastamento para pós-graduação stricto sensu? 
3. Houve **aproveitamento** de ação de capacitação **estritamente referente à pós-graduação stricto sensu no período letivo cursado pelo servidor durante o 1º semestre de 2023**, compreendido entre 27/2/2023 e 29/7/2023? Detalhar. 
4. Em caso de não aproveitamento de ação de capacitação, conforme questionamento do item 3, **o 1º semestre** letivo do ano de 2023 **seria passível de cassação**, nos termos dos normativos vigentes? 
5. Outras informações relevantes ao caso, se houver. 

             - Nota-se que **para o servidor**, a DGER pediu que se manifestasse sobre **'ausência de atividades acadêmicas no 1º semestre de 2023'**. Na página 1486, pede **ao ILB** que se manifeste conclusivamente a respeito de **'eventual descumprimento da ação de capacitação pelo servidor'**. Afinal, qual é o motivo de o servidor sofrer o processo? A acusação é sobre 'ausência de atividades acadêmicas' ou 'descumprimento de ação de capacitação'? Se foi ausência de atividades acadêmicas, porque a pergunta sobre descumprimento? Se a acusação é de descumprimento, porque fui inquirido sobre atividades acadêmicas na manifestação prévia? Mais importante que isso, qual é a norma que vincula a conduta do servidor a um ou a outro aspecto? Por que a norma não foi citada? **A DGER falta com lisura no processo, ao pedir que o servidor se manifeste sobre um ponto, mas ao fim o acusa de outro**. Não pode haver 'descumprimento de ação de capacitação' porque o curso ainda não terminou!
             
             - Em qual dispositivo do anexo IV está definido o "descumprimento de ação de capacitação" relativo a afastamentos para doutorado? Pelo texto do capítulo que versa sobre afastamentos para pós-graduação stricto sensu, o critério é obtenção ou não obtenção do título.
             
             - **Se a acusação** contra o servidor é sobre descumprimento de **ação de capacitação** ou ausência de atividade acadêmica, então **por que** a DGER inquire o ILB sobre prazos de apresentação de **atestado médico**?! Outro motivo não informado ao servidor, para que se manifeste?
             
             - Se a apresentação de **documentação médica** tempestivamente ao Senado é uma questão relevante para apurar a responsabilidade, **porque a DGER pergunta** sobre esses documentos ao **ILB, que é órgão de capacitação**, e não se dirige ao **SIS**, que é o serviço de saúde? Não seria mais apropriado?
             
             - Quanto ao item 1, a DGER embasa seu questionamento no artigo 4º do Ato da Comissão Diretora nº 17/2011, porém o referido ato foi revogado pelo artigo 2º do Ato da Comissão Diretora nº 10/2017. Por sua vez, o ADG nº 26/2017 citado pelo ILB não é atinente ao caso, pois o servidor não solicitou licença médica. Sua situação estava em conformidade com o Decreto-Lei 1044/1969. A cobrança reiterada acerca da tempestividade do envio de documentação médica pelo servidor para autorização de licença para tratamento de saúde é, portanto, indevida. A Casa foi notificada da enfermidade e da internação hospitalar do servidor nos termos do art. 30 do Anexo VI do ATC 14/2022, o que pode ser comprovado por meio dos extratos do SIS. Não se pode falar então em comunicação tardia, nem em desconhecimento dos fatos. E em se tratando de documentos custodiados pela própria Administração, há vedação legal à exigência de que sejam apresentados pelo servidor. Por oportuno, causa estranhamento o fato de a DGER inquirir o ILB e não o SIS, que é o sistema ou serviço integrado de saúde. p. 1486
             - Quanto ao item 2, desconhece-se norma que exija com obrigatoriedade que o servidor que continua regularmente matriculado no doutorado requeira suspensão ou interrupção, seja do afastamento ou da própria ação de capacitação, sob nenhuma circunstância - nem por motivo de saúde nem por semestre em que não houve conclusão de disciplinas. O Despacho nº 4139/2024-DGER não apresentou a motivação normativa em que a DGER fundamenta tal cobrança (p.1487). Tampouco o fez o ILB ao responder à pergunta da DGER (p.1771). Ao que tudo indica, portanto, trata-se de uma exigência arbitrária.     
             - Quanto ao item 3 e ao item  4, o servidor já apresentou exaustivamente as atividades acadêmicas realizadas durante o 1º semestre de 2023, o que inclui atividades em disciplinas do curso, a realização de trabalhos e pesquisas, o cumprimento de requisitos formais do regulamento da pós-graduação, como a publicação de artigo em anais de Congresso Científico, entre outras. Desconhece-se norma aplicável que vincule necessariamente a ação de capacitação de doutorado à aprovação em disciplinas, que exija cumprimento semestral de créditos em disciplinas ou ainda que invalide as atividades realizadas pelo servidor como atividades de ação de capacitação. Conforme o regulamento do curso, que já consta nos autos, ressaltamos que há atividades obrigatórias para a obtenção do título de doutor que não são realizadas em disciplinas formais matriculáveis nem adicionam créditos ao histórico acadêmico. Tal como acontece em relação ao item 2, o Despacho nº 4139/2024-DGER não apresenta a motivação normativa em que a DGER fundamenta a exigência dos itens 3 e 4. A esse respeito, acrescentamos que o inciso I, do art. 16, do ADG nº 17/2021 determina aplicação de penalidade "no período em que não houver comprovação de **qualquer** ação de capacitação formal realizada pelo servidor". O dispositivo não menciona como requisito para fins de comprovação os atributos "com aproveitamento" ou "estritamente referente à pós-graduação stricto sensu", os quais constam no Despacho da DGER nº 4139/2024 e no Ofício do SEPOS/COESUP/ILB nº 94/2024-SEPOS/COESUP/ILB - ambos os documentos acrescentam as duas especificações sem qualquer referência às normas que supostamente as fundamentam. Ao que tudo indica, portanto, também são exigências arbitrárias. Logo, nos termos do inciso I, art. 16 do ADG nº 17/2021, conclui-se que o servidor apresentou comprovação suficiente de suas atividades acadêmicas realizadas no 1º semestre de 2023 - entendendo 'suficiente', no caso das atividades realizadas e comprovadas pelo servidor, como mais atividades comprovados do que 'qualquer' comprovação exigida no normativo.                      
             
             Para conclusão: Isso revela a permanência, no final do processo, da mesma situação que o servidor identificou no encaminhamento inicial em que o ILB remeteu os autos 'para deliberação' da DGER: a completa ausência de materialidade na acusação, a inexistência de motivo factual e jurídico para punir o servidor. O prolongamento do processo contra o servidor desde outubro de 2023 até o começo de 2025 sem qualquer fundamento ou motivação, culminando numa decisão desarrazoada que penaliza o servidor revela grave violação de nosso ordenamento jurídico. Foram afrontados todos os princípios basilares da Administração Pública (impessoalidade, legalidade, transparência/publicidade, eficiência e moralidade), e inúmeros outros princípios constitucionais (devido processo, ampla defesa, juízo imparcial, reserva legal, anterioridade da Lei, irretroatividade, segurança jurídica, vedação ao retrocesso social, vedação ao comportamento contraditório, confiança legitima). A liberdade e a fluidez com que juntos os dois órgãos internos da burocracia do Senado violam a Constituição deve soar um alerta a toda a comunidade legislativa.  
             
             se tal exigência tem sido feita a todos os servidores que passam ou passaram por processo de licença ou afastamento 
 
             
             RASF art. 130, § 2º:
             § 2º Ato da Diretoria-Geral regulamentará os **procedimentos e prazos** relativos às licenças previstas em lei.
             
             RASF art.132, inciso II, § 3º:
             § 3º Ato da Diretoria-Geral regulamentará os **procedimentos e prazos** relativos aos afastamentos previstos em lei.
             
             Sobre a ADG 17/2021:
             - A norma não menciona comprovação de ação de capacitação formal com aproveitamento, ela menciona a comprovação de qualquer ação formal de capacitação (vide art. 16, caput). 
             - o art. 14, §1º, inciso I determina que o ILB deve descrever os fatos e indicar o dispositivo regulamentar infringido pelo servidor e o §2º diz que isso deveria ocorrer no prazo máximo de 30 dias, o que não aconteceu nem a partir dos fatos nem a partir da ciência dos fatos (data de entrega do relatório de atividades acadêmicas do 1º semestre de 2023).  
            ADG 17/2021 Art. 14. O descumprimento dos requisitos normativos e dos 
termos do deferimento da ação de capacitação deverá ser submetido à deliberação da Diretoria-Geral. § 1º O ILB instruirá os autos para: I - descrever os fatos e indicar o dispositivo regulamentar 
infringido pelo servidor; II - referenciar o termo de compromisso firmado pelo servidor 
que contenha declaração de pleno conhecimento e ciência da norma regulamentar e dos termos da ação de capacitação deferida; III - analisar os argumentos apresentados na manifestação prévia do servidor. § 2º O descumprimento das obrigações normativas pelo servidor deverá ser comunicado pelo ILB à Diretoria-Geral no prazo máximo de 30 (trinta) dias, contados de sua ocorrência ou do termo do prazo final para a comprovação da ação de capacitação autorizada.
     Art. 16. Será cassada a licença ou o afastamento: I - no período em que não houver comprovação de **qualquer** ação de capacitação formal realizada pelo servidor; II - no período em que for apurada ação de capacitação cuja carga horária semanal seja inferior à mínima definida no RASF; III - que ultrapassar o período autorizado para a conclusão da 
ação de capacitação; IV - quando o objeto da ação de capacitação, o período ou a 
instituição promotora forem divergentes do estabelecido no deferimento da autoridade competente; V - quando houver qualquer alteração unilateral da ação de 
capacitação deferida, sem a prévia autorização da autoridade competente (não houve alteração unilateral, a ação continuava a mesma); VI - quando for averiguado o descumprimento dos requisitos 
legais e normativos, bem como o descumprimento dos termos do deferimento da ação de capacitação; VII - quando não forem acolhidas as justificativas para a interrupção da ação de capacitação; VIII - quando não houver o efetivo retorno ao serviço 
decorrente de conclusão antecipada ou interrupção requerida para a ação de capacitação; IX - quando não houver comprovação formal da ação de 
capacitação autorizada, nos termos do RASF, deste Ato e do deferimento. (...) Art. 17. O ILB e a Diretoria-Geral editarão ato conjunto para 
atendimento ao disposto no inciso V do caput do art. 46 do Anexo IV do RASF, no prazo de 60 (sessenta) dias a contar da vigência deste Ato. 
Art. 18. As regras estabelecidas no Ato da Comissão Diretora 
nº 11, de 2021, **aplicar-se-ão aos requerimentos para a concessão de licença para capacitação e para a participação em atividades de capacitação que forem devidamente protocolados a partir da data de vigência do referido Ato**.        

             - O artigo 10 do ADG 17/2021 dispõe que: 

>"Art. 10. Na exclusiva hipótese de caso fortuito ou força maior, devidamente justificada e comprovada, o servidor **poderá requerer** a interrupção da licença para capacitação. § 1º O requerimento de interrupção obriga o servidor à comprovação da ação de capacitação realizada até a data anterior ao pedido. § 2º O servidor deverá retornar imediatamente ao serviço, mediante notificação de sua chefia imediata e comunicação ao ILB." 

O texto trata exclusivamente de licença capacitação. Mas ainda que fosse sobre afastamento para pós-graduação, o texto **faculta** ao servidor a opção de pedir ou não a interrupção em caso fortuito. Caso faça a requisição para interromper, deve retornar ao serviço imediatamente e comprovar a ação de capacitação realizada até a data anterior ao pedido.

             Em qual normativo da Casa está definido que o servidor afastado para pós-graduação, quando ficar doente, não poderá tratar-se e continuar os estudos? E qual é o dispositivo que determina que em caso de doença, o servidor deverá pedir suspensão ou interrupção de seu afastamento? Até onde entendo, a Lei 8112/1990 não prevê suspensão ou interrupção de afastamento. Uma vez interrompido, ou o servidor concluiu o curso, ou não concluiu - caso em que deverá apresentar justificativa da não conclusão. A lei 8112/1990 tampouco estabelece possibilidade de que o servidor retorne ao afastamento após interrupção. Se isso tem acontecido com base no dispositivo de suspensão de licenças, é importante atentar que se tratam de institutos diferentes, cada um com seus procedimentos. Se a Administração induz o servidor a retornar do afastamento para daí a algum tempo sair de novo, a Administração o estará induzindo a erro. Ao retornar, o servidor precisa ter terminado o curso e para sair, só após o interstício de tempo em serviço equivalente ao tempo afastado. Será razoável esperar que em 2 anos de mestrado ou 4 de doutorado nenhum servidor vá adoecer, ou se acidentar, ou sofrer uma perda familiar? E se adoecer, será do interesse público que peça interrupção do curso, desperdiçando o tempo que já ficou ausente, os recursos que já foram investidos e retorne sem o título? Acaso acredita-se que no Senado, o servidor estará imune à doença? Qual é a falta disciplinar que o servidor comete se ficar doente durante o afastamento? Por que motivo será punido com a interrupção de seus estudos?!
             - No meu caso, não houve interrupção de atividades acadêmicas. Durante o tratamento médico, minhas ausências foram compensadas pela realização de exercícios domiciliares determinados pelo Coordenador do curso, o que me permitiu continuar com os estudos, conforme se vê nos e-mails anexados ao fim de minha manifestação prévia. Tal direito me é garantido pelo Decreto-Lei 1044 de 1969. Por isso, pergunto-me qual fundamento normativo teria eventual pedido de suspensão com imediato retorno às atividades no Senado? E qual utilidade isso teria para o avanço no curso, para minhas atividades no Senado ou para o tratamento de minha doença? A alternativa que a DGER parece sugerir teria o único efeito de me desligar do curso de doutorado, transformando em desperdício o investimento de tempo que fiz e de recursos, qu e já feito, por mim e pelo Senado. , pois eu ainda assim precisaria me ausentar do Senado para o tratamento médico. 
             - Se, enquanto estava ainda enfermo, solicitei alternativa para acompanhar a matéria à distância, se a Coordenação do curso designou exercícios domiciliares para compensar minhas ausências durante o tratamento médico, então por que eu solicitaria a interrupção do curso, conforme a pergunta da DGER sugere? 
             
             - Exercícios domiciliares são método legítimo para aferição de presença quando o estudante se encontra impossibilitado por alguma condição de saúde de frequentar as aulas. As condições para isso são: que a instituição de ensino concorde, que tenha condições de acompanhar o aluno em situação especial e que o conteúdo ministrado seja compatível. Não parece adequado, portanto, que o Senado puna o servidor por exercer seu direito regular estabelecido no Decreto-Lei 1044/1969.
              
             - Se por outro lado, com as menções aos termos 'suspensão' e 'interrupção' a DGER se referir ao trancamento, então volto mais uma vez a afirmar: não hove suspensão nem interrupção de atividades. Como já dito e demonstrado na manifestação prévia, o pedido de trancamento ocorreu no fechamento do semestre, quando já não havia mais aulas. No momento em que o trancamento foi deverido e efetivado pela Universidade, já estávamos em plena atividade no segundo semestre, matriculados e cursando regularmente as disciplinas do novo período. Tais atividades não foram interrompidas nem de forma alguma afetadas pelo trancamento, e assim seguiram até o fim do segundo semestre. Note-se, a esse respeito, que o mesmo documento em que a Universidade anuncia haver realizado o trancamento, anuncia também, em contiguidade, haver realizado o retorno do aluno à atividade. Desse modo, não houve interrupção de atividades nem em tese nem na prática. Ao longo do ano de 2023 não houve 1 dia letivo sequer em que, havendo aula, o servidor estivesse desvinculado de disciplinas, com matrícula suspensa ou irregular. 
             - Alegações de 'ausência de atividades acadêmicas' não correspondem à verdade dos fatos, como já demonstrado na manifestação prévia. Já a alegação de que o servidor descumpriu ação de capacitação é improcedente porque a ação de capacitação é o doutorado, não é o semestre. Assim como não cabe exigir dos servidores em licença capacitação que apresentem teses de doutorado, não cabe a pretensão de avaliar os semestres de doutorado como se fossem cursos livres, autosuficientes e independentes do restante do curso. Aliás, uma pesquisa em processos de colegas afastados e licenciados demonstra o completo casuísmo desta exigência, violação clara do princípio da isonomia.  
             - Tratar um trancamento justificado por motivo de saúde como "descumprimento de ação de capacitação" é atitude arbitrária e contrária à legislação. O trancamento justificado por motivo de saúde é uma medida inserida no âmbito da autonomia didático-pedagógica e administrativa da Universidade. Trata-se de uma salvaguarda contra sanções acadêmicas que garante certa proteção a alunos que passam por enfermidades, que já passaram ou que enfrentam dificuldades em decorrência delas. 
             - DGER repete algumas vezes ao longo do processo que o servidor esteve "apenas" um mês sob "atestado médico", de um período letivo que foi de 27/02/2023 a 29/07/2023 (5 meses). Mas, como se vê no calendário acadêmico da pós-graduação da UnB no 1º semestre de 2023^[https://www.saa.unb.br/images/documentos/pos-graduacao/calendario/atividade/2023/2023_1_Calend_Atv_PosGrad_27_03_2023.pdf], as aulas tiveram início em 28/03, após o período de matrículas e podiam se estender até 25/07. As disciplinas em que o servidor estava matriculado tiveram suas últimas aulas em 13 e 17/07^[pp. 1414-1415 do Processo NUP 00200.003561/2020]. Sabendo que a prescrição médica foi de 30 dias de recuperação, e contando os dias do começo das aulas até o último dia de cada matéria, conclui-se que o período doente corresponde a cerca de 28 a 30% do período de aulas das duas disciplinas. Como parâmetro de comparação, a Resolução nº 4, de 16/9/86, do então Conselho Federal de Educação estima em 25% o limite máximo de ausências para não prejudicar a progressão do aluno. 
             - Ao longo do processo, a DGER menciona algumas vezes a proporção entre tempo em recuperação e quantidade de dias de aula no 1º semestre de 2023, apontando que havia mais dias de aula do que o atestado médico cobria. Sim, e por isso o servidor continuou estudando. 
             - Subjacente à fala da DGER está um julgamento arbitrário sobre a adequação do pedido de trancamento e uma cobrança arbitrária de comunicação prévia ao pedido. São arbitrários porque as normas internas do Senado não dispõem sobre aceitabilidade, adequação nem sobre procedimentos para pedidos de trancamento. As normas internas do Senado não adentram no assunto, por entenderem tratar-se de questão regulada pelos normativos da Universidade e, portanto, circunscrita à autonomia universitária estabelecida na Constituição Federal. Está, portanto, fora da competência de normas infralegais. Em se tratando de um recurso previsto pela Universidade para os casos específicos em que pode ser aplicado, o trancamento justificado é uma ferramenta para a administração da vida acadêmica, mas também para assegurar condições adequadas para o aprendizado. Assim, revela-se medida de cunho didático-pedagógica, pela qual a Universidade reconhece uma situação fora do controle do estudante, a qual impactou ou poderá impactar negativamente sua formação acadêmica. Ao conceder o trancamento justificado, a Universidade isenta o aluno de responsabilidade por não obter aprovação na disciplina.  Se a Universidade, cuja atividade precípua é o ensino, reconheceu a excepcionalidade da situação e isentou o servidor, deve perder objeto a intenção de o punir, além de carecer de razoabilidade e de fundamento. Será competência dos servidores na administração do Senado julgar adequação de medida didático-pedagógica e administrativa adotada pela Universidade? A resposta é não, isso segundo a Constituição. E os normativos internos, que dizem? Se a política de capacitação da Casa rege-se pela economicidade e pela indisponibilidade do interesse público, não parece adequado custear um serviço com chefia, doze servidores, terceirizados e estagiários para realizar uma atividade de controle que a Universidade já faz rotineiramente. Menos ainda se a atuação desse serviço induz a Casa a conclusões contraproducentes. Por exemplo: concluiu-se que o servidor deveria não ter pedido o trancamento justificado por motivo de saúde. Isso implica, então, que quando o servidor ficou doente, deveria 'retornar imediatamente ao serviço' para permanecer doente no Senado ao invés de permanecer doente na universidade. Faria diferença? Não, o servidor ainda assim precisaria se ausentar e buscar tratamento de sua saúde durante exatamente o mesmo período de tempo. Contudo, essa opção desperdiçaria dois anos de sua dedicação pessoal, de investimentos do Senado, mais de um ano de tramitação do processo que autorizou seu afastamento, horas de trabalho de servidores em vários setores da Casa, uma vaga num programa de doutorado avaliado com a nota máxima da CAPES numa das mais importantes instituições de ensino e pesquisa do país, e a possibilidade de conclusão do doutorado, privando a Casa e a sociedade de usufruir os resultados da formação do servidor. 
             Se a legislação fala que não se cobrará ressarcimento do servidor que, por motivo de força maior, não obtiver o título (isto é, do servidor que já não tiver mais possibilidade alguma de concluir o curso), a DGER precisa justificar o motivo de estar cobrando ressarcimento do servidor que ficou doente e, por causa da doença, trancou apenas um semestre. Se motivos de força maior isentam de responsabilidade um servidor que não concluiu um curso inteiro, não é razoável nem proporcional responsabilizar o servidor que não concluiu apenas um semestre. Acaso um semestre apenas é suficiente para determinar cumprimento e descumprimento, se o doutorado dura 8 semestres? 
             Se há penalidade para descumprimento da ação de capacitação, e no caso a ação de capacitação autorizada é o doutorado, por que motivo a DGER processou e puniu o servidor antes do doutorado acabar? Qual é a norma que proíbe o servidor de solicitar o trancamento? Qual é a norma que exige que o servidor se matricule em disciplinas e obtenha aprovação em todos os semestres? Se as normas permitem que um servidor obtenha afastamento para trabalhar exclusivamente na tese ou para realizar pesquisa para a tese sem ter matrícula em disciplinas (e, por consequência, sem obter aprovação nelas), por que a DGER está exigindo que o servidor se matricule e obtenha aprovação em disciplinas todos os semestres? Por que não reconhece a pesquisa e o artigo realizados pelo servidor como atividade de capacitação? Se o regulamento do doutorado exige a publicação de artigos, por que a DGER afirma que o artigo publicado pelo servidor não é atividade regular do curso? Uma tese em Ciência Política, em média, tem 150 a 200 páginas. No processo do servidor há mais de 300 páginas de textos produzidos durante o doutorado, incluindo análise de dados de survey. Qual a base da DGER para determinar que esses textos e análises produzidos pelo servidor não farão parte da tese? É uma grave sucessão de arbitrariedades, com uma punição igualmente arbitrária aplicada ao servidor, que juntas devem qualificar a atuação da DGER como crime de abuso de autoridade. 
             Quem está agindo conforme as leis: o servidor que usou direito concedido pela Universidade para contornar consequências da doença e prosseguir à conclusão do curso, ou o ILB e a DGER, que cerca de um ano antes do prazo terminar, já começaram a acusar e a processar o servidor? Estarão atuando conforme as leis e com imparcialidade, se as normas isentam de responsabilidade por motivos de força maior os servidores que estão em afastamento para estudo? 
             O trancamento justificado é, portanto, um direito que a Universidade concedeu ao servidor, em conformidade com a legislação vigente e com a autonomia universitária. Os gestores da parte administrativa da Casa não podem se insurgir contra o servidor que estava no exercício de um direito regular seu. Tratam-se de excludentes de ilicitude tanto o exercício do direito regular, quanto o desempenho de suas atribuições como servidor público e discente no estrito cumprimento das normas da Universidade. Além disso, os gestores da DGER e do ILB não podem ampliar obrigaçoes nem reduzir direitos dos servidores por meio de atos, portarias, despachos ou ofícios, porque são matérias cuja competência originária é da legislação em sentido formal, e porque a atribuição de legislar não é delegável. 
             
             
             - Não se pode confundir licença para tratamento de saúde com trancamento geral justificado por motivo de saúde. No caso do servidor, não houve necessidade de solicitar licença para tratamento porque suas ausências foram compensadas com a realização de exercícios domiciliares, nos termos do Decreto-Lei 1044 de 1969. 
             
             1) a licença para tratamento de saúde - requer atestado médico e tem a duração indicada pelo profissional responsável pelo atendimento ao paciente, ou pela junta médica revisora. É uma medida prevista no regulamento administrativo e no estatuto do servidor relacionada à **Saúde**; 
             
             2) no caso concreto, o tratamento da saúde do servidor ocorreu em paralelo com a realização de exercícios domiciliares para aferir frequência às aulas. O direito a tratamento médico é um direito social reconhecido na Constituição relacionado à **Saúde**. Já os exercícios domiciliares para compensar ausências escolares decorrentes de condições de saúde é um direito social associado a uma **medida de educação** com o objetivo conjunto de restaurar condições físicas saudáveis e reduzir o impacto da enfermidade sobre a rotina do estudante ou, ao menos, facilitar a retomada de suas atividades quando estiver recuperado (requer atestado médico ou comprovação da situação de saúde, depende da concordância de dirigente da instituição de ensino e, se a situação for passageira, pode vincular o período coberto pelos exercícios ao tempo previsto para recuperação);  
             
             3) o trancamento geral justificado de matrícula, solicitado pelo servidor discente ao término do semestre: é uma **medida de educação** cujo objetivo é sanear ou combater os prejuízos causados por casos fortuitos e motivos de força maior à formação acadêmica do estudante. Incide sobre período letivo integral (isto é, não há fracionamento do trancamento), mas não anula do histórico escolar do aluno o registro das disciplinas trancadas como atividade curricular. A concessão do trancamento não depende de quantidade de dias de atestado médico, o critério é a comprovação da enfermidade (ou de outro fator impeditivo que independa da vontade do estudante) que tenha impactado ou possa impactar o desempenho discente.   a Universidade                                                                            
             
             - O período de aulas efetivamente só se inicia após a conclusão do processo de matrículas, que compreende a organização da oferta de disciplinas, distribuição de ementas, abertura de prazo para matrícula em disciplinas, a análise e autorização dos pedidos pelos orientadores. Devido a esses procedimentos no 1º semestre de 2023, as aulas tiveram início em 28/03, e os professores tinham até 25/07/2023 para cumprir a carga horária e aplicar avaliações, tendo em seguida até 29/07 para finalizar as menções e consolidar o registro das turmas. , embora ano início das aulas em 28/03/2023. administrativa  direito do servidor discente garantido pela Universidade após análise da documentação médica, reconhec em procedimento próprio, no qual se reconhece a excepcionalidade da situação alheia à vontade do aluno  justificado e ocorre em reconhecimento, na esfera pública, da enfermidade como motivo de força maior que prejudicou o rendimento do servidor Promover procedimento administrativo contra servidor que esteve doente, havendo provas claras e suficientes de sua situação de saúde, e sabendo que, mesmo durante a enfermidade, o servidor desempenhou atividades acadêmicas superando dificuldades debilitantes, não é apenas arbitrariedade reiterada e prolongada, é um crime de abuso de autoridade.  A tentativa continuada de atribuir irregularidade a servidor que precisou de atendimento médico de emergência é uma violação do maior e mais importante preceito de nossa constituição: o direito de preservação da vida. Atacar servidor que  em missão fora, cedido,  uma vio  de provas claras, e sabendo que ele desempenhou suas atividades acadêmicas mas não conseguiu passar persegui-lo A tentativa reiterada de estabelecer essa relação configura-se em possível abuso de autoridade - sobretudo diante das provas que já apresentei e dos esforços que empreendi para dar continuidade às atividades acadêmicas apesar das dificuldades decorrentes
             Quanto ao segundo ponto inquirido ao ILB, o servidor não solicitou suspensão nem interrupção da ação de capacitação, por que a ação de capacitação continuou. 
             
             - Como o afastamento ainda estava em curso, o art. aplicável era o 41, que dispõe sobre o envio de relatórios ao ILB, a apresentação de comprovantes de frequencia quando solicitado e de outras informações, **quando solicitado**. A questão que o despacho da DGER não indicou foi: qual informação, afinal, foi **solicitada** pelo ILB e o servidor não forneceu?!
             
             - ass
             - o fluxo previsto no processo, conforme e-mail ja´ citado do SEATUS, antes da manifestação prévia, seria: "finalizada a instrução, o interessado será notificado para apresentar sua manifestação prévia e, havendo manifestação, o processo seguiria para o órgão responsável pela instrução se pronunciar e depois para a DGER decidir" - copiar normas internas e leis do processo administrativo a esse respeito. 
             - ao invés de seguir o rito processual definido nas normas que a própria DGER formula, conhecido e divulgado pelos servidores do SEATUS-Processos, a DGER achou por bem 'aproveitar' que o ILB havia demorado a devolver o processo com relatório e incluir novas acusações na fase de 'relatório', sem dar ao servidor a oportunidade de contestar as novas acusações.

p. 1487 - fim do despacho da DGER, assinado por Ilana na data 19/11/2024

p.1499 - 1500 - assinado pelos servidores do ILB entre 12 e 13 de novembro de 2024
             00200.003561/2020-66 (VOLUME 1) - 00100.206670/2024-95


p. 1501 - ofício de Marcos André assinado em 18/11/2024, respondendo ao ILB sobre documentos comprobatórios do término do doutorado

p. 1766 - ILB solicita mais prazo para responder, em 27/11/2024. Pelo que lembro, prazo já estava estourado, sem justificativa. Deve-se considerar que a última manifestação do ILB no processo havia sido nas páginas 1499 e 1500, no dia 13/11, e que o próprio ILB adicionou 1767-1504=263 páginas entre a manifestação anterior e o pedido de prazo adicional, sendo que essas 263 páginas não acrescentam nenhuma informação que já não estivesse no processo: uma lista de alunos da pós-graduação em Ciência Política da UnB contendo o nome do servidor, o que já estava provado pela declaração de aluno regular emitida pela Universidade, e a programação do Congresso Mundial de Ciência Política constando o nome do servidor como apresentador oral, fato que também já estava comprovado pelo certificado emitido pela IPSA com o nome do servidor, incluído no relatório de atividades acadêmicas do 1º semestre de 2023.

Então além do grosso da informação adicional desde a última vez que o ILB esteve com o processo ter sido inserida pelo próprio ILB, não há novidades que requeiram grandes análises, pois eram informações que já estavam no processo. Isso configura ineficiência processual e atitude protelatória, com a conivência da DGER que autorizou o prazo extra.

p. 1767 - DGER concede mais 5 dias, em 28 de novembro de 2024, prazo terminou em 04 de dezembro

p.1769 a 1781 - ILB responde em 05 de dezembro de 2024 o despacho nº 4139/2024-dger
             00200.003561/2020-66 (VOLUME 1) - 00100.206670/2024-95

item 1: 
> Conforme pode se depreender dos autos, o atestado médico foi apresentado ao ILB, no semestre subsequente, juntamente com as prestações de contas – Relatório de Atividades Acadêmicas do 1º semestre de 2023, no qual foi informado o ato de trancamento de matrícula.(...) Não se identificou nos autos comprovação de que o atestado médico tenha sido submetido ao Senado Federal nos termos do art. 4º do Ato da Comissão Diretora (ATC) nº 17, de 2011 p.1770

Resp: o mesmo que foi dito sobre o item no despacho da DGER.

item 2:
> Não se identificou nos autos e não se tem notícia sobre requerimento dirigido ao Senado Federal contendo pedido de suspensão ou de interrupção da ação de capacitação objeto do afastamento para pós-graduação stricto sensu ou ainda de suspensão ou de interrupção do próprio afastamento desde o ato autorizativo até a presente data. Cumpre informar que o ILB somente tomou conhecimento do trancamento geral da matrícula (correspondente ao período acadêmico de 27/2/2023 a 29/7/2023) e das alegadas questões de saúde, ocorridas ao longo do 1º semestre de 2023, após cobrança da prestação de contas das atividades acadêmicas.

Resp: Nesse item, o ILB assevera que somente após ter cobrado informações acadêmicas e outras questões referentes ao 1º semestre de 2023, o servidor **prestou as informações** que deram ciência ao ILB sobre fatos ocorridos naquele período, nos termos do inciso III, do art. 41, do Anexo IV, do ATC 14/2022 ("prestar outras informações a respeito de suas atividades acadêmicas **que forem solicitadas pelo Instituto Legislativo Brasileiro**"). A chamada "prestação de contas" compreendeu também o envio do **relatório de atividades** propriamente dito e do **comprovante de frequência**, nos termos dos incisos I e II, do mesmo artigo. **Isso comprova que**, ao receber a solicitação de informações oriunda do ILB, **o servidor cumpriu todos os deveres regulamentares** afeitos à sua condição de estar em afastamento e durante o curso, conforme acha-se inscrito nos incisos I a III, do art. 41, do anexo IV, do ATC 14/2022 (RASF). Consequentemente, qualquer alegação de descumprimento de obrigação relativa ao afastamento é improcedente. A prestação adequada das informações que foram solicitadas pelo ILB foi cumprida pelo servidor, conforme está devidamente atestado nas próprias afirmações do órgão no trecho citado acima, do ofício 94/2024.    

item 3:
> Diante das informações a serem elencadas a seguir, considera-se que não houve aproveitamento de ação de capacitação estritamente referente à pós-graduação stricto sensu no período letivo cursado pelo servidor durante o 1º semestre de 2023, compreendido entre 27/2/2023 e 29/7/2023.(...) Não foram identificadas nos autos informações que elucidem o aproveitamento de disciplinas acadêmicas anteriormente cursadas pelo servidor para fins de avanço alternativo no quantitativo de créditos exigidos, ao longo do 1º semestre de 2023 (...). Quanto ao desempenho acadêmico (...), do ponto de vista de avanço no cumprimento de créditos letivos previstos no regulamento do doutorado em tela, o trancamento representou, de forma objetiva, a progressão nula dos créditos acadêmicos relativos à matrícula no semestre (...) o servidor também afirma que, durante o 1º semestre acadêmico de 2023, houve participação em produção científica, tendo sido “(...) aprovado com artigo em Congresso Mundial de Ciência Política” (...). Por fim, o servidor afirmou no documento que finalizou “o 2º Artigo Científico obrigatório” e que naquele momento procurava “(...) publicação ou evento acadêmico para divulgá-lo.” Observa-se que o Regulamento do Programa de Pós-Graduação em Ciência Política da UnB menciona “publicar dois artigos” [grifo nosso]. Portanto, o artigo que o servidor informa ter sido publicado no “27° Congresso Mundial da IPSA” teria resultado no cumprimento parcial do requisito especificamente presente no art. 28, inciso I, do Regulamento do Programa supracitado, para a obtenção do título de doutor. O servidor incluiu no processo o certificado de participação no referido Congresso como “Paper Author and Oral Presenter”. No programa do evento acadêmico (...) consta o nome do servidor (...)  como autor do artigo  (“paper”) intitulado “Social Cross-Affiliations and Political Outcomes: Measuring Intersectionality-Effects on Political Opportunities and Behaviour”. O servidor também informou esse título em sua prestação de contas. Ainda na prestação de contas apresentada pelo servidor em relação ao 1º semestre de 
2023 estão apenas insertados dois textos acadêmicos assim intitulados: “Intersectionality: Theory and Conceptual Framework” e “Modelos Hierárquicos Generalizados: teoria e aplicação para análise de determinantes dos resultados eleitorais”. O artigo que o servidor alega ter sido publicado no Congresso do IPSA não consta na íntegra da prestação de contas apresentada referente ao 1º semestre de 2023.

Resp: O mesmo que foi dito na resposta à DGER sobre exigências arbitrárias (obrigatoriedade de obtenção de créditos, de aprovação em disciplinas, de demonstração semestral de aproveitamento, de solicitar interrupção ou suspensão do curso ou do afastamento, de apresentar documentos para licença médica sem ter solicitado a licença, etc.  não estão previstas/os nos normativos. Assim como não há impedimento a pedir trancamento, nem punição por não obter aprovação e créditos em todos os semestres, ...). À falta de normas prévias que tornem esses itens exigíveis ou proibidos, adiciona-se resposta aos comentários do ILB sobre as atividades acadêmicas do servidor. Conforme já dito, não se achou norma que requeira que o servidor comprove em todos os semestres ter obtido aprovação em disciplinas, nem que exija como condição para o afastamento o acúmulo de créditos semestrais obrigatórios - isto não se justifica porque há norma que permite que servidores obtenham afastamentos exclusivamente para escrever ou fazer pesquisa para a tese, e não há exigência de que se matriculem nem obtenham aprovação em disciplinas. Por que se faria, então, tal exigência exclusivamente do servidor, em prejuízo da impessoalidade nos atos administrativos? Por fim, ressaltamos que o inciso I, do art. 16, do ADG 17/2021 determina a aplicação de punição nos períodos em que não houver comprovação de **qualquer** ação de capacitação, sem distinções de 'aproveitamento' ou de serem 'estritamente relacionadas ao curso'. Além das provas da realização de atividades acadêmicas no 1º semestre de 2023 que o servidor apresentou em sua manifestação prévia, o ofício nº 60/2024-SEPOS/COESUP/ILB relata várias atividades comprovadamente desempenhadas pelo servidor, o que, apesar da mudança de postura do órgão, também é corroborado pelo ofício 94/2024. Nesse último ofício, o ILB entra em contradição com o ofício 60/2024, que não questionou nenhum dos argumentos nem das provas apresentadas pelo servidor. É sintomático o reposicionamento do órgão sem que nada dos fatos analisados haja mudado entre uma e a outra manifestação no processo. Além da incoerência entre os documentos, também há incoerência interna no ofício 94/2024. Ao mesmo tempo em que esse ofício diz que não houve comprovação de ação de capacitação com aproveitamento (p.1771) e por isso o ILB opina pela possibilidade de cassação (p.1774), nele o ILB admite que o servidor apresentou informações sobre artigo científico publicado naquele semestre(p.1772), admite que com isso há cumprimento parcial de requisito regulamentar obrigatório para a obtenção do título de doutor (p.1773), reconhece que há prova da participação do servidor na programação do Congresso científico (p.1773), informa que o servidor apresentou dois artigos de sua autoria na "prestação de contas" (p.1773), e afirma que o servidor incluiu no processo, nada mais nada menos que: o certificado de sua participação no Congresso Mundial de Ciência Política!! (p.1773). Há, portanto, um claro conflito interno na mudança de posicionamento do ILB. O resultado é a evidente desconexão entre os fatos que o ILB comenta e a conclusão a que chega, no tocante à responsabilização e à possibilidade de punição do servidor. Independentemente de sua incoerência, o ofício 94/2024 cumpre a função de atestar que o servidor comprovou ter realizado várias ações de capacitação no período e, portanto, não é punível, nos termos do inciso I, do art. 16, do ADG 17/2021. 

Registra-se o fato de que os apontamentos trazidos pelo ILB aparecem tardiamente no processo. Embora alguns sejam até pertinentes e merecessem atenção (p.ex. inserir documento da Universidade atestando cumprimento de requisito de produção acadêmica; esclarecimento e resolução do conflito de títulos do artigo apresentado, etc.) O momento oportuno para eles, dentro do rito processual e das formalidades necessárias ao procedimento administrativo, deveria ter sido na fase de instrução - antes da manifestação prévia do servidor, quando ele poderia, então, apreciá-las. Inserir tais considerações na fase do relatório prévio desvirtuou mais uma vez o processo já tão maculado. o servidor não teve chance de apreciá-las nem apresentar contestação pois logo em seguida foi tomada uma decisão. Aliás, o fato de, nesse contexto, a DGER haver aceito os argumentos tardios do ILB em inovação da acusação sem propiciar o direito do servidor ao contraditório e antes de tomar a decisão; e, mais que isso, o fato de a DGER haver incentivado a manifestação do ILB mais de uma vez no processo em prejuízo da defesa do servidor, o qual recebeu diferentes acusações em mais de uma rodada durante a fase processual do relatório, mas só teve uma chance para apresentar contestação, um ano atrás, sobre apenas um aspecto da acusação; combinado com o fato de a DGER, com a reformulação e reedição da lista de perguntas feitas ao ILB, haver direcionado o conteúdo e o sentido do relatório que foi apresentado por aquele órgão no processo; todos esses aspectos somam-se para configurar: 1) o completo vício do procedimento conduzido pela DGER e instruído pelo ILB, e 2) a motivação suficiente para anulá-lo junto das decisões e injustiças que produziu.

item 4 - p. 1774 e 1775

> Sim, o não aproveitamento de ação de capacitação no 1º semestre letivo de 2023 seria passível de cassação do referido período de afastamento do servidor, pela DGER, nos termos do art. 16 do Ato da Diretoria-Geral (ADG) 17, de 2021, que trata da regulamentação do Anexo IV do RASF (Ato da Comissão Diretora nº 14/2022 e atualizações). Consoante o dispositivo normativo retromencionado: 
“Art. 16. Será cassada a licença ou o afastamento: 
I - no período em que não houver comprovação de **qualquer** ação de 
capacitação formal realizada pelo servidor; 
II - quando a carga horária total executada for inferior à carga horária 
total autorizada para a referida licença ou afastamento; (Redação 
dada pelo Ato da Diretoria-Geral nº 30/2023). 
III - cuja ação de capacitação executada exceder a data inicial ou final 
da respectiva licença ou afastamento; (Redação dada pelo Ato da 
Diretoria-Geral nº 30/2023). 
IV - quando o objeto da ação de capacitação, o período ou a instituição 
promotora forem divergentes do estabelecido no deferimento da 
autoridade competente;
V - quando houver qualquer alteração unilateral da ação de 
capacitação deferida, sem a prévia autorização da autoridade 
competente; 
VI - quando for averiguado o descumprimento dos requisitos legais e 
normativos, bem como o descumprimento dos termos do deferimento 
da ação de capacitação; 
VII - quando não forem acolhidas as justificativas para a interrupção 
da ação de capacitação; 
VIII - quando não houver o efetivo retorno ao serviço decorrente de 
conclusão antecipada ou interrupção requeridas para a licença para 
capacitação; (Redação dada pelo Ato da Diretoria-Geral nº 30/2023). 
IX - quando não houver comprovação formal que ateste a conclusão 
exitosa da ação de capacitação autorizada, nos termos do RASF, deste 
Ato e do deferimento. (Redação dada pelo Ato da Diretoria-Geral nº 
30/2023). 
Parágrafo único. Para atendimento ao disposto no § 3º do art. 52 do 
Anexo IV do RASF: (Redação dada pelo Ato da Diretoria-Geral nº 
30/2023). 
I - na hipótese do § 7º do art. 52 do Anexo IV do RASF, considerar-se
á 1 (um) dia de cassação para cada 1 (um) dia de ação de capacitação 
excedente às datas inicial ou final da licença ou afastamento deferidos 
ao servidor; (Incluído pelo Ato da Diretoria-Geral nº 30/2023) 
II - em se tratando de descumprimento dos demais requisitos 
regulamentares, considerar-se-á a proporcionalidade entre a carga 
horária das ações de capacitação reconhecidas pela Administração e 
a carga horária total contida no deferimento da respectiva licença ou 
afastamento. (Incluído pelo Ato da Diretoria-Geral nº 30/2023).” 
[Grifo nosso].

Resp: Já vimos que o inciso I deste art. 16 do ADG 17/2021 é precisamente o dispositivo que torna improcedente a punição ao servidor. Conforme temos apontado, na manifestação prévia o servidor apresentou comprovação de várias ações de capacitação realizadas no 1º semestre de 2023. Adicionalmente, os ofícios 60 e 90/2024-SEPOS/COESUP/ILB acabam por reconhecer também que o servidor comprovou a realização de ações de capacitação naquele período (ainda que o último se posicione contra o servidor). 
Fora esse aspecto, destaca-se da resposta do ILB que o órgão aplicou ao caso uma versão do texto normativo editada após os fatos que estavam em análise!
A redação trazida pelo ILB ao processo foi dada ao ADG nº 17/2021 pelo ADG nº 30/2023, curiosamente editado no dia 20 e publicado no dia 23 de outubro de 2023, exatamente os mesmos dias em que, respectivamente, o ILB deu início ao procedimento administrativo contra o servidor, e encaminhou os autos à DGER para "deliberação". 
Mesmo se a demora de duas semanas do SEPOS para encaminhar o processo tiver sido coordenada com a edição dos atos, os princípios da segurança jurídica, da reserva legal e da anterioridade da lei determinam que punição só se aplica se houver lei prévia que a determine, e vedam a aplicação de sanções ou restrições de direitos retroativas. Isso implica que o texto do normativo aplicado pelo ILB não pode servir como parâmetro para julgar e decidir acerca de fatos ocorridos entre abril e agosto de 2023, quando estava vigente o texto normativo anterior (anterioridade da Lei, legalidade, ultratividade). Note-se que o conteúdo da redação final atualizada do normativo citado pelo ILB passou a contornar as principais críticas que fiz às exigências da DGER e do ILB no processo, para torná-las exigíveis. A alteração, ao que tudo indica, foi feita para viabilizar as cobranças que DGER e ILB fizeram ao servidor. Contudo, a aplicação retroativa de normativo para impor obrigação, proibição, restringir direitos ou penalizar é violação constitucional do princípio da irretroatividade, inscrito nos incisos LIV e LV, do art. 5º da Constituição Federal. 
Na verdade, é questionável até mesmo se o ADG 17/2021 aplica-se ao caso do servidor, visto que seu afastamento (05/04/2021) é anterior a essa regra (16/07/2021).
Como o estado 'em afastamento' do servidor precede a norma ADG 17/2021, e essa norma "estabelece" punições, obrigações e vedações, isto é, trata da regulação/restrição de direitos e liberdades, então o princípio da ultratividade dita que o caso do servidor seja regido pelo ordenamento vigente à época em que se deu início o afastamento. Isso torna descabida a aplicação do ADG 17/2021 ao caso concreto, entendimento corroborado pelo artigo 18 desse ato, que afirma que a norma aplica-se aos requerimentos de capacitação protocolados a partir de sua data de vigência do referido ato (16/07/2021). 


p. 1776 - cita: 

art. 4º do anexo IV do RASF (ATC 14/2022)
> Art. 4º O planejamento, o acompanhamento e a avaliação 
permanentes da capacitação dos servidores, no âmbito do Senado 
Federal, constituem competências intrínsecas de cada órgão da 
estrutura administrativa e atribuição indissociável de todos os seus 
diretores, coordenadores e demais gestores da instituição, sob a 
coordenação técnica do Instituto Legislativo Brasileiro. 
Parágrafo único. Para o exercício de suas funções, o Instituto 
Legislativo Brasileiro contará com o Comitê Científico-Pedagógico e 
com o Conselho de Supervisão, com atribuições e composição definidas 
no Regulamento Administrativo, além de outras conferidas pelas 
demais normas relativas ao funcionamento do ILB.” 

art. 58 do anexo IV do RASF (ATC 14/2022)
> “Art. 58. O Instituto Legislativo Brasileiro e a unidade responsável pela 
gestão de pessoas do Senado Federal devem desenvolver, 
conjuntamente, procedimentos de controle e registro da participação 
dos servidores em ações de capacitação. 
Parágrafo único. Em caso de descumprimento injustificado, pelo 
servidor, dos deveres expressos nos arts. 32, 41, 42 e 52 deste Anexo, o 
ILB dará ciência à Diretoria-Geral, que poderá deliberar a imediata 
suspensão dos vencimentos do servidor a ser executada pela unidade 
responsável pela gestão de pessoas, sem prejuízo das medidas 
anteriormente previstas."

p.1777 - cita:
art. 41 e 42 do anexo IV do RASF (ATC 14/2022)
para participação em programas de pós-graduação stricto sensu, são estipuladas as seguintes obrigações de prestação de contas, nos termos do Anexo IV do RASF (Ato da Comissão Diretora nº 14/2022 e atualizações), aos beneficiados com o instituto previsto no artigo 96-A da Lei Federal nº 8.112, de 1990:  
> “Art. 41. São deveres do servidor, durante o período de afastamento:  
I - enviar ao Instituto Legislativo Brasileiro relatório de atividades acadêmicas, incluindo eventual produção acadêmica já realizada;  
II - enviar ao Instituto Legislativo Brasileiro comprovante de frequência ao curso, quando solicitado;  
III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro. 

> Art. 42. São deveres do servidor, após a conclusão do curso:
I - entregar, em até sessenta dias após a conclusão do programa, cópia da dissertação ou tese aprovada para a obtenção da titulação;  
II - executar ação de disseminação e aplicação do conhecimento adquirido na pós-graduação, quando requisitado pelo Instituto Legislativo Brasileiro, nos termos do § 8º do art. 19 deste Anexo;  
III - prestar outras informações a respeito de suas atividades acadêmicas que forem solicitadas pelo Instituto Legislativo Brasileiro.” [Grifo nosso]. 

p.1777 - ILB relembra o termo de compromisso, firmando a resposabilidade quanto a obrigações, (com grifo nos relatórios semestrais de atividades)

> " De modo a ratificar a importância das prestações de contas parciais e final, demonstrando seu vínculo e seu desempenho acadêmico, o servidor afastado de suas funções laborais (para se dedicar exclusivamente à participação em programa de pós-graduação stricto sensu com a manutenção integral de sua remuneração) assina termo de compromisso e o entrega juntamente com seu requerimento de afastamento. No termo de compromisso, o servidor requerente manifesta conhecimento e assume a responsabilidade quanto ao cumprimento de obrigações, as quais derivam das disposições contidas no Anexo IV do RASF (Ato da Comissão Diretora nº 14/2022 e atualizações). Ademais, a Portaria do ILB nº 1, de 2017 estipula que os relatórios a serem entregues por servidor afastado para participação em programa de pós-graduação stricto sensu possuem periodicidade semestral: 
“Art. 11. O beneficiado com quaisquer dos afastamentos previstos nesta Portaria deverá enviar ao ILB durante o período de afastamento: 
**I - relatórios semestrais de atividades avaliados pelo orientador acadêmico, incluindo eventual produção acadêmica já realizada;** 
II - comprovante de frequência ao curso, quando solicitado; 
III - outras informações que forem solicitadas a respeito de suas atividades acadêmicas.” [Grifo nosso].  

p. 1778 - Depois de citar o PIL 1/2017 e o art. 41 do anexo IV do RASF, o ILB alega que o último relatório de atividades acadêmicas enviado ao ILB pelo servidor foi relativo ao segundo semestre de 2023. 

- alega que servidor não inseriu no processo informações sobre o exame de qualificação, nem sobre a defesa de trabalho final de curso, e acrescenta que o servidor está inadimplente em relação à prestação de contas do 1º semestre de 2024

Resp: É importante perceber que o ILB e a DGER retiveram o processo indefinidamente desde 17/06/2024, arrastando-o até janeiro de 2025. Em dezembro, ainda não haviam tomado nenhuma decisão, pelo contrário, ainda estavam tramitando o processo de um para o outro sob pretexto de dar ao ILB mais prazo para analisar os autos, então com 1700 páginas. Só que o ILB havia se manifestado no processo cerca de 15 dias antes, e desde então, das 200 a 300 páginas inseridas no processo, 95 a 99% foi o próprio ILB que inseriu. Será que os 80 dias que reteve o processo até vencer o prazo de afastamento do servidor não foram suficientes para o ILB se familiarizar com os autos? O ILB havia recebido o processo com a manifestação prévia do servidor em 17/06/2024. O processo ficou desse dia até o dia 28/08/2024 sem receber instrução, e desse modo ficou parado no órgão sem prosseguir à DGER para decisão por tempo suficiente para vencer o prazo máximo de afastamento do servidor. Há e-mail do servidor alertando a DGER sobre seus receios com relação à atuação do ILB, mas nada foi feito e os receios se cumpriram. O prazo final previsto do afastamento chegou, mas a pendência de análise dos autos pelo ILB e a consequente inexistência de decisão sobre o 1º semestre de 2023 impediram o servidor de requerer prorrogação antes do prazo terminar. Então, o servidor apontou uma inconstitucionalidade cometida pelo Senado na implementação de seu afastamento (ao deferir o afastamento tardio, vários meses após o início previsto, o prazo foi implementado retroativamente, impondo uma contagem de prazo ficto de afastamento a períodos de tempo já passados, incidindo sobre o registro dos dias já trabalhados previamente pelo servidor). Com base nisso, o servidor pediu que a DGER determinasse a manutenção do prazo já autorizado de afastamento, porém contado em dias e a partir da data de publicação da decisão de autorizar o afastamento. Ocorre que enquanto o ILB reteve o processo que apurava responsabilidade sobre os eventos do 1º semestre de 2023, a DGER reteve o que decidia sobre o ajuste do prazo de afastamento, ambos sem qualquer definição a respeito do que deveria fazer o servidor naquela situação.

Sem publicar nem comunicar qualquer decisão a respeito dos processos, a DGER determinou aos órgãos subordinados em sua estrutura que abrissem novos processos contra o servidor, decorrentes da irresolução dos primeiros: alegando para isso faltas injustificadas e até mesmo abandono de cargo. Manteve os primeiros processos indefinidos, sem decisão, e não publicou que era sua a determinação de abertura dos novos processos, impedindo o servidor de conhecer sua decisão. O servidor, por sua vez, não podia retornar por conta própria ao serviço sem justificativa, pois poderia ser penalizado (encerramento injustificado, retorno prematuro, etc), já que a qualquer momento poderia sair a decisão de seu pedido de correção dos prazos. Tampouco podia continuar ausente sem que a DGER regularizasse sua situação. 


Tal situação se arrastou durante meses do ano 2024, durante os quais os apelos do servidor por informações acerca do andamento do processo e sobre sua situação pesssoal relativa ao afastamento e à possibilidade de continuar o curso de doutorado foram ignorados completamente. Nem mesmo após a última participação do ILB no processo e antes da deliberação pela DGER foi cumprido o dever de dar ao servidor a possibilidade de se opor, apresentar contestação, produzir provas, inquirir testemunhas, etc., enfim, de exercer o direito de se defender das novas acusações que DGER e ILB haviam costurado tardiamente no processo. Quando o servidor interviu junto ao assessor da DGER encarregado e pediu carga no processo para poder se manifestar, foi completamente ignorado e não recebeu resposta nenhuma.

A retenção dos processos sem movimentação ou avanço, o cerceamento dos direitos do servidor para se defender, e do direito de fazê-lo diante de um juízo imparcial, junto com as práticas persecutórias por autoridades abusivas e o retardamento processual fazem parecer que os dois órgãos se articularam para produzir, com seus atrasos, a alegada situação de inadimplência com que agora julgavam poder acusar o servidor e aplicar-lhe punição. A tentativa do servidor em se manifestar antes da decisão da DGER iria frustrar o objetivo do grupo, pois o servidor poderia sanear a alegada inadimplência, entregar o relatório de 2024, apresentar os documentos reclamados - ainda que não houvesse norma os exigindo, enfim, poderia desfazer antecipadamente qualquer pendência, e regularizar o que supostamente não estivesse regularizado. Mas foi ignorado porque o interesse dos envolvios não parecia ser corrigir o que precisasse de correção. Ao que tudo indica, o objetivo era aplicar punição e prejudicar. 

(apesar de que a DGER poderia ter atravessado a manifestação do órgão e ter decidido, com base na lei 9874/99) s o processo ficou parado na DGER desde 28 de agosto sem nenhuma decisão, atuando para causar ineficiência processual, comutando decisão de um processo ao outro, como se a decisão de regularidade 

*Cadê o raciocínio acerca da vigência e abrangência do PIL 1/2017?

Sobre o envio de relatórios de atividades para subsidiar o monitoramento feito pelo ILB, recordamos instrução processual feita pelo ILB antes da manifestação prévia, acerca do cumprimento de obrigações pelo servidor. Lá está consignado que "os relatórios de todos os períodos até o momento estão nos autos". Então, não há inadimplência do servidor nesse quesito. O que há, da parte do servidor, conforme já relatado na manifestação prévia, é a reclamação da ineficiência gerada pela confecção destes relatórios                                                                                                                                                                O procedimento foi aberto para apurar os fatos ocorridos no primeiro semestre de 2023. O fato de a acusação estar indeterminada, sem objeto e sem fundamento, não autoriza o ILB nem a DGER a alterarem o escopo do que foi discutido até então para incluir fatos alheios àquele período, os quais não foram discutidos ao longo do processo. Menos ainda, se esses fatos que querem incluir são problemas decorrentes da própria atuação do ILB e da DGER.


p. 1780 - ILB reproduz decisão da DGER de 'prorrogação". 

Da decisao da DGER, deve-se atentar para: a inconstitucionalidade do caráter "improrrogável" da decisão da DGER: 1) falta isonomia, pois outros pós-graduandos, que nem passaram por período de enfermidade, obtiveram prorrogação; 2) vai contra a lei 9784/99, segundo a qual todo administrado tem o direito de peticionar perante o Estado, de ter o seu pedido considerado e respondido com a devida justificativa - a decisão administrativa no processo, antes que eu sequer solicite a prorrogação; 3)  se a data de início foi alterada, então pedido atendeu minha solicitação e deveria deslocar o prazo final igualmente. Se não o fez, então reduziu meu prazo de afastamento sem justificativa, prejudicando minha formação. Se o fez, entao não houve prorrogação, foi apenas a contagem do prazo já previsto de afastamento, a partir da publicação. 

Verificar: 41 NUP 00100.203816/2024-41. e 42 NUP 00100.211102/2024-14. 



p. 1782 a       - Despacho nº 4511/2024-DGER com decisão final

p. 1782
             - cita art. 41 do anexo IV do RASF (ATC-14/2022)
             - cita art. 11 do PIL nº 1/2017:
             Art. 11. O beneficiado com quaisquer dos afastamentos previstos nesta 
> Portaria deverá enviar ao ILB durante o período de afastamento: 
I - relatórios semestrais de atividades avaliados pelo orientador acadêmico, incluindo eventual produção acadêmica já realizada; 
II - comprovante de frequência ao curso, quando solicitado; 
III - outras informações que forem solicitadas a respeito de suas atividades acadêmicas. (Grifou-se)

> "em estrito cumprimento de suas atribuições regulamentares, o Instituto Legislativo Brasileiro, semestralmente, solicitava ao servidor o encaminhamento de relatório parcial das atividades acadêmicas realizadas." p.1783

> "relativa ao 1º semestre de 2023, (...)  o servidor apresentou Relatório de Atividades Acadêmicas2, no qual relatou haver sido acometido por enfermidade durante o referido semestre, o que teria prejudicado seu aproveitamento nas disciplinas cursadas, acarretando a necessidade de trancamento de matrícula junto à instituição de ensino. Informou ainda sobre as **atividades acadêmicas desenvolvidas no período, as quais não se relacionam com a efetiva elaboração da tese de doutorado, uma vez que não se tratou da evolução da pesquisa ou da redação da tese.**" p.1783

p.1783

             - O argumento da DGER, tal como o do ILB, é logicamente dependente da premissa de que eu não tinha realizado nenhuma atividade acadêmica no 1º semestre de 2023. Por isso, há tanto esforço e malabarismo com a intenção de descaracterizar e invalidar as atividades desempenhadas naquele período. Na medida em que houve atividade, adicionam exigência de que seja "com aproveitamento". Se teve aproveitamento, acrescentam: "exclusivamente relacionada ao curso". Se tinha relação com o curso, contestam: "falta declaração da Universidade confirmando". Aí, quando a Universidade atesta, eles emendam: "mas o título tá diferente". E da outra, que tem o mesmo título, dizem: "essa é só parcial, não foi publicada". Assim, eu ficaria correndo em círculo, até eu mesmo tropeçar. 
             - Para sustentar a pretensão punitiva, tanto o ILB quanto a DGER precisaram executar malabarismos e acrobacias argumentativas, umas mais outras menos bem finalizadas. A violação que a DGER comete, nesse parágrafo da p. 1783 é grotesca nesse sentido. A fim de manter a insustentável alegação de que o servidor não desempenhou atividades acadêmicas, a DGER viola constitucionalmente a autonomia universitária, a liberdade de pensamento e de expressão do servidor-autor, para, em claro abuso de autoridade, determinar que: 

>             "as atividades acadêmicas desenvolvidas no período (...) não se relacionam com a efetiva elaboração da tese de doutorado, uma vez que não se tratou da evolução da pesquisa ou da redação da tese" (p.1783).

Após citar trecho do relatório de atividades de 1º/2023, em que digo que talvez precise utilizar mais meses do que previsto no pedido inicial para poder finalizar o curso. Com a citação, DGER apoia e justifica atitude do ILB em 'informar' à DGER quanto ao trancamento geral de matrícula do 1º semestre de 2023, "com potencial impacto no cumprimento do objeto que ensejou o ato autorizativo, dentro do prazo deferido". 

- Pareceria algo bem razoável de se fazer, de fato. A DGER só não mencionou que o encaminhamento não foi para informação, foi para deliberação; e, sendo para deliberação, não disse sobre o que, por que, nem como, nem com quem. Não há, até o momento, informação sobre qual é a norma infringida, nem sobre ato ou omissão que configuram a infração, e muito menos sobre a vinculação lógica pela qual o ILB atribuiu vínculo entre fato e norma. 

- a DGER recebeu o encaminhamento incompleto com os autos, do ILB, apesar de esse encaminhamento ter chegado sem os elementos formais básicos estabelecidos no art. 10, do ADG 17/2021. Na hipótese de que ainda fossem recolher indícios que apontassem provável irregularidade, então, o mesmo art. 10 do ADG 17/2021 estabelece que o ILB tinha 30 dias para informar à DGER o ocorrido. No dia 06/10/2023, o servidor apresentou seu relatório referente ao 1º semestre daquele ano. Pois bem, em 20/10/2023 o SEPOS encaminhou o processo para o DEXILB e de lá o processo foi à DGER. Mas esse encaminhamento não notificou nada, visto que não acusou o servidor: não apontou a norma infringida nem o fato. Tanto é que a DGER devolveu o processo com perguntas para o ILB especificar qual era afinal a situação. Após analisar os autos mais uma vez e responder a DGER, o ILB ainda não apontava qual era a norma violada. A DGER então elaborou os termos de uma possível infração e pediu que o servidor se manifestasse. A hipótese aventada pela DGER foi contestada com provas e argumentos. O processo retornou com a resposta do servidor à DGER, que por sua vez pediu nova análise do ILB. Dois meses e doze dias depois, o ILB devolveu ainda sem conseguir especificar qual era a irregularidade afinal. Perceba-se que o prazo estipulado pela DGER na norma (30 dias) já se esgotou há muito tempo. A DGER continuou insistindo em receber o caso contra o servidor sem os elementos formais necessários e ainda fora do prazo que ela própria havia estipulado. Depois disso, o processo passou na DGER mais de 80 dias e foi tramitado de volta ao ILB, também sem especificar a irregularidade cometida pelo servidor e sem decidir finalmente pôr fim ao processo.  Frisamos: o processo foi e voltou mais de uma vez sem que os órgãos da Administração da Casa especificassem se havia ou não irregularidade que o servidor houvesse cometido. O processo deveria ter sido anulado. Quando há referência a normas nos documentos inseridos pelo ILB e pela DGER nesse processo, elas ocorrem de forma genérica, apontando princípios gerais, ou elas não são aplicáveis, porque já foram revogadas, porque correspondem a outros tipos de licença e/ou afastamento, ou porque , ou quando são específicas (art. 41 a 43 do anexo IV do RASF), não apontam nenhum dos fatos ocorridos em 2023 como irregularidade. A continuidade do processo nessas condições configura desvio de finalidade, violação da impessoalidade e abuso de poder! 

p.1784
- Após resumo em que se menciona a irresignação do servidor quanto ao encaminhamento dos autos à DGER, afirma-se:

> Quanto a isso, cabe esclarecer que é dever regulamentar do ILB reportar situações em que se constata o não aproveitamento de ação de capacitação à Diretoria-Geral, a quem compete analisar a situação fática e as justificativas apresentadas com o intuito de averiguar eventual descumprimento de obrigação e determinar a adoção de medidas pertinentes, ainda que se trate de afastamento em andamento. 

- O servidor não se opôs de forma alguma a que DGER fosse informada e pudesse acompanhar seu afastamento. A irresignação com o encaminhamento feito pelo ILB deveu-se ao fato de que os responsáveis pelo encaminhamento do processo à DGER naquele órgão não especificaram de forma alguma qual era o delito que o servidor supostamente havia cometido. Em nenhum momento, o ofício que na época o ILB encaminhou à DGER mencionava "não aproveitamento de ação de capacitação", nem "descumprimento de obrigação". Tais formulações foram elaboradas pela DGER já em momento bem posterior do processo, após a manifestação prévia do servidor. O ILB tinha conhecimento das atividades realizadas pelo servidor no período questionado e não descreveu a situação com esses termos que a DGER usou posteriormente. Outro ponto de insatisfação foi a seletividade e parcialidade do ILB no relato feito à DGER sobre aquele período: concentrou-se exclusivamente nas informações 

- ainda a respeito disso, o trecho da DGER parece insinuar que o "não aproveitamento de ação de capacitação" é irregularidade punível, que pode implicar em "descumprimento de obrigação", e que é possível fazer julgamento de eficácia/ineficácia, aproveitamento/não-aproveitamento de "afastamento em andamento". Como já apontamos, são asseverações repetidas pela DGER ao longo do processo. Porém, em nenhum momento vieram acompanhadas de sua fundamentação jurídica e normativa. A palavra aproveitamento não aparece em trechos do anexo IV que se refiram a afastamentos para pós-graduação. Em qual dispositivo encontra-se a exigência de aprovação em disciplinas em todos os semestres do doutorado? Em qual dispositivo o critério de aproveitamento é definido nesses termos pelo Senado? Em qual dos incisos que estabelecem obrigações aos servidores afastados para pós graduação (arts. 41 e 42) do anexo IV do RASF se enquadra a dita obrigação de aprovação/aproveitamento? A falta de menção às normas que fixam tais exigências faz parecer que são cobranças feitas exclusivamente ao caso em tela - o que é vedado, por ofender o princípio da impessoalidade. 

p. 1785

Para fundamentar sua resposta, a DGER cita trechos do ofício nº 23/2024-SEPOS/COESUP/ILB - NUP 00100.054291/2024-11. 


             p.1786-1796
             
             - resume a situação: "não concluiu atividades letivas com êxito no doutorado. Não constam no processo comprovação da qualificação do projeto de tese nem ata de defesa da tese, as 'prestações de contas' até 2º de 2023 estão nos autos; no processo não consta documento de comunicação do servidor ao ILB ou a outro órgao da Casa sobre licença para tratamento de saúde a ser previamente deferida pelo Senado Federal ou requerimento com esse propósito; apresentou cópia da solicitação de trancamento datada de 19/07/2023 em 06/10/2023; servidor diz que foi afastado por 30 dias por motivo de saúde durante o primeiro semestre de 2023, o que contribuiu para um desfecho negativo seguido de seu pedido de trancamento; servidor diz que houve atividade acadêmica formal durante o semestre, dado que cursou disciplinas, bem como cumpriu obrigações relativas à produção científica; acusa o ILB de tumulto processual por adicionar documentação repetida e fora de ordem, bem como por instruir os autos de maneira a prejudicar sua imagem e distorcer os fatos; diz que não há inadimplência quanto às suas obrigações regulamentares e que entregou todos os relatórios; que as obrigações dispostas no art. 42 do anexo iv do RASF são deveres após a conclusão do curso, e portanto não exigíveis durante o curso; que não se aplicaria ao seu caso a penalização de ressarcimento conforme hipóteses previstas no art. 43 do anexo iv do rAsf; disse ainda que estava em situação regular e que iria concluir o curso, havendo ainda prazo; disse que sua conduta não está tipificada como irregularidade nas normas vigentes; e que o relatório de atividades é o único dever do servidor em pós-graduação previstos nas normas com autonomia para iniciativa, sendo os demais prestados após provocação; disse que não havia clareza nas normas quanto à necessidade de comunicação prévia dos eventos ocorridos em 2023; disse que apresentou documentos de saúde à UnB, já que suas obrigações imediatas e compromissos laborais no período eram presencialmente lá na universidade; em seguida a DGER perguntou 4 itens ao ILB como "análise efetiva e pormenorizada de mérito quanto à manifestação do interessado": 1) se apresentou atestado médico tempestivamente (em até 2 dias) ao Senado, nos termos do art.4º do ATC 17/2011; 2) se apresentou prévia e formalmente um requerimento de suspensão ou interrupção da ação de capacitação? 3) se houve 'aproveitamento' estritamente referente à pós-graduação no 1º semestre/2023; 4) se não houve aproveitamento, o 1º semestre de 2023 é passível de cassação? - nas respostas, DGER copia as do ILB, que já foram comentadas.
             
             
            p.1797
            
> em relação às ações de capacitação patrocinadas pelo Senado Federal com recurso público, **está expresso de forma taxativa a sua vinculação à indisponibilidade do interesse público e sua utilização de modo econômico**. Nesse sentido, fica evidente a relevância do controle administrativo sobre todo o desempenho acadêmico dos servidores que se afastam para realizar ação de capacitação em curso de pós-graduação stricto sensu. Com efeito, o zelo pelo escasso recurso público é obrigação que se impõe à Administração. Por conseguinte, tais disposições, que constituem norteadores da Administração Pública, vinculam a concessão e o acompanhamento da capacitação de servidores do Senado Federal, com destaque para os incisos VIII e X do art. 3º do Anexo IV19 do RASF. 
             
             - Exatamente! Concordância plena. Isso nunca foi ponto de discussão da parte do servidor. A questão dada é justamente sobre a adequação do acompanhamento que tem sido feito. Veja, por exemplo, que teses em Ciência Política têm em geral entre 150 e 300 páginas. Espera-se que a tese, enquanto trabalho de conclusão do doutorado, seja o principal resultado do curso. Assim, geralmente é a atividade que mais demanda esforços, tempo e dedicação do pós-graduando. Agora veja que o número de página que antecede meu relatório do 1º semestre de 2023, no processo, é 1001. Isso significa que o processo de **acompanhamento** do doutorado, só nos dois primeiros anos de curso, já ultrapassava 1000 (mil) páginas. Nessa conta ainda não estão computadas as outras 800 páginas inseridas no processo desde outubro de 2023 até o presente.  Não é possível considerar adequado um processo de acompanhamento na metade do curso com mil páginas, sobretudo quando se considera que a extensão de uma tese gira em torno de 1/3 ou mesmo 1/4 desse total. Há claramente aí um problema de dosimetria, uma calibração errada entre acompanhamento e atividade principal. A atividade principal deve ser o foco, porque ela é o resultado com que o doutorando contribui para a sociedade, ao contrário dos processos de acompanhamento - que demandam tempo, disputam a atenção do discente, reduzem a capacidade de dedicação à atividade principal, acrescentam pouquíssimo às informações já contidas em declarações emitidas pela Universidade e, principalmente, não terão utilidade quando o curso acabar. Os argumentos da economicidade e do interesse público são relevantes, mas será que esses princípios realmente apontam para a adequação dos moldes do monitoramento feito atualmente? O interesse público nessa questão já está positivado: representantes eleitos pelo povo brasileiro aprovaram o estatuto do servidor público. Nele está o dispositivo que abre a possibilidade da pós-graduação stricto sensu como uma das vias para a Administração Pública capacitar seus quadros. O mesmo estatuto também estabelece o que é 'descumprimento', nesse caso, digamos: a não obtenção "culposa" do título e a "evasão de cérebros". A punição para isso também está definida: o ressarcimento dos gastos ao erário. Aí está o monitoramento adequado ao interesse público e à economicidade. Tudo o que passa disso, ainda que com aparência de zelo, é desperdício de dinheiro público. 
             Ao estudar os normativos internos, percebi que desde 2021, quando se iniciou meu afastamento, tem havido uma escalada de rigor nas normas adotadas na Casa para regular a capacitação dos servidores. Mas não nos enganemos: a crescente complexidade é faca de dois gumes. Cada nova exigência acrescida às normas precisará de pelo menos um procedimento novo que monitore e assegure seu cumprimento, outro que comprove ou satisfaça a exigência e pelo menos mais um que o avalie. A isso, adicione-se a estrutura normativa: 1) fragmentada em diferentes textos;  2) de diferentes instâncias (ADG, ATC, PIL, RES);  3) imprecisa acerca de sua competência originária (limites da delegação feita pela lei: procedimentos de seleção dos cursos e prazos? impossibilidade de restringir direitos e criar deveres?). Dessa forma, quanto mais complexa se tornar a estrutura normativa, mais intensiva será a demanda por mão de obra dedicada e por recursos públicos necessários à sua observância. 
             Disso resulta que, para a finalidade de acompanhamento das ações de capacitação do Senado, a atividade de fiscalização e o encrudescimento das normas não andam no mesmo sentido e direção da economicidade e do interesse público. Para compreender que os gastos com a atividade se tornam ineficientes, basta lembrar que as Universidades já exercem rotineiramente a atividade de controle sobre a produtividade dos alunos. Há um limite máximo de permanência, há critérios de frequência, quantidade mínima de créditos a obter por semestre, etc. e há punição prevista para os casos de descumprimento, uma delas é o desligamento do curso - que equivale à não obtenção do título dentro do prazo previsto. A estrutura de acompanhamento criada na Casa tem atribuições redundantes em relação às rotinas de registro acadêmico já desempenhadas pela Universidade dentro de suas atribuições precípuas, também inscritas na autonomia universitária estabelecida na Constituição. 
             Logo, ao orientar-se pelos princípios da economicidade e do interesse público não deveria conduzir a política de capacitação do Senado rumo à escalada normativa, mas ao controle das ações de capacitação na exata medida prescrita na Lei 8112/1990 - nem mais, nem menos, em harmonia também com os princípios da legalidade e da reserva legal. Não há como saber o que resultaria do cenário alternativo de forma objetiva. Contudo, no caso concreto, vê-se que a produtividade acadêmica do servidor foi consideravelmente maior nos períodos anteriores à intervenção do ILB e poderia ter continuado assim.                                                                                                                                                                                              
           
p. 1800 - 

> Ressalta-se que o servidor é totalmente afastado de suas atribuições, mantendo integralmente sua remuneração, e que todo o período é contado como de efetivo exercício, garantindo-se, assim, sua dedicação exclusiva aos estudos e demais atividades demandadas pela ação de capacitação. Por esse motivo, mostra-se contrapartida bastante razoável que haja monitoramento constante da ação, para aferir o êxito no seu aproveitamento contínuo, o que é apurado pela Administração a cada semestre, consoante deveres do servidor dispostos no art. 41 do Anexo IV do RASF c/c art. 11 da Portaria do ILB nº 1/2017. 

Sobre o monitoramento, reafirma-se o compromisso do servidor, que sempre prestou todas as informações que lhe foram solicitadas e entregou todos os relatórios esperados, conforme o próprio ILB já afirmou em outras ocasiões.

> Por conseguinte, não se coadunam com os princípios da moralidade, da eficiência, da transparência e da indisponibilidade do interesse público, que o servidor se comporte como se não houvesse obrigação de, tempestivamente, informar quaisquer ocorrências que, efetiva ou potencialmente, prejudiquem ou que, em algum modo, comprometam o seu desempenho acadêmico ou a continuidade da ação de capacitação autorizada. 

É despropositada a afirmação de que o servidor se porta como se não houvesse obrigação de informar o Senado. Ressalta-se em primeiro lugar, haver declaração do ILB atestando a regularidade do servidor em relação à prestação de informações e demais obrigações paara o semestre em questão. Em segundo lugar, destacamos o fato de nesse quesito, DGER e ILB valerem-se de normas não pertinentes a internação hospitalar de emergência e não apresentarem indicação da norma que obrigaria o servidor a: 1) solicitar a suspensão ou interrupção do trancamento; ou 2) que vede a não obtenção de créditos em disciplinas; ou 3) que invalide a participação em disciplinas sem obtenção de créditos enquanto atividade acadêmica; ou 4) ainda que determine a comunicação em caso de doença ou trancamento. 



É fora de propósito a alegação do ILB acerca de relatório de 2024 e cobrança de documentos sobre 'conclusão' do curso. O ILB tem ciência do processo aberto em que solicito ajuste no prazo de afastamento, e isto se dá, obiamente, porque o curso não acabou, mas principalmente, porque o próprio ILB e a DGER retiveram a posse do processo sem participação do servidor desde 17 de junho de 2024 - ignorando inclusive pedidos do servidor para se manifestar no processo antes da decisão da DGE, no que foi ignorado. 


p.1801- 

> "A bem da verdade, somente após ser cobrado pelo ILB e intempestivamente, o servidor prestou contas referente ao 1º semestre letivo de 2023, ocasião em que passou a ser de conhecimento do Senado Federal a sua opção pelo trancamento de matrícula do referido semestre.  De igual modo, somente na referida prestação de contas o servidor apresentou o atestado médico parcial (30 dias) para justificar o não aproveitamento de todo o período do   afastamento (de 27 de fevereiro 2023 a 29 de julho de 2023), em desacordo com as disposições do art. 3º do Ato da Diretoria-Geral (ADG) nº 2622, de 2017, que obriga a submissão de atestado médico à apreciação da Junta Médica do SF, no prazo máximo de 2 dias úteis." 

> Resumo do restante: falou das disciplinas sem obtenção de 'aproveitamento'; falou da ausência de informação institucional que indique cumprimento de requisito de produção acadêmica obrigatória no referido período e eventuais créditos obtidos no semestre. por fim, o servidor limitou-se a juntar atestado parcial e intempestivo ao SF, nos termos do art. 3º do ADG nº 26 de 2017.

Mais uma vez, a arbitrária cobrança do envio de informação fora do relatório sem que o ILB haja solicitado previamente. Não cabe, não há previsão disso nas normas

p. 1802

> Veja que eventual comprometimento da ação de capacitação exige que o servidor submeta as possíveis razões e seus efeitos ao crivo da avaliação da autoridade competente do órgão ao qual está vinculado, na condição de servidor efetivo. **Não se admite que o servidor adote posição de absoluta independência em relação ao Senado Federal e considere que deva satisfações ou que exista relação de subordinação apenas em relação à instituição de ensino.** A instituição de ensino tem autoridade sobre a avaliação do desempenho acadêmico, mas não substitui, em nenhuma hipótese, a autoridade funcional do Senado Federal sobre o servidor. (...) Dessa forma, **o ato de trancar matrícula perante a instituição UnB não constitui fundamento autônomo para afastar o servidor de suas obrigações de prestar contas junto ao Senado Federal**. Todo e qualquer fato relevante e que tenha potencial de interferir nas atividades acadêmicas, seja para suspender ou interromper a ação de capacitação, deve ser informado imediatamente ao Senado Federal. Em especial, o servidor deve prontamente informar à Administração as situações que tenham repercussão ou que eventualmente possam prejudicar o desempenho acadêmico satisfatório e/ou o efetivo  aproveitamento do período letivo semestral para a obtenção do título de doutorado para o qual foi afastado das suas atribuições laborais. A avaliação desses fatores e justificativas apresentadas submetem-se ao juízo discricionário do Senado Federal.  

Compreende-se o que a DGER quis dizer. Conforme já afirmado anteriormente, o servidor está plenamente disposto a estreitar a comunicação acerca de seu doutoramento. Porém continua não achando justa a manifestação de que há esta expectativa somente após os eventos daquele semestre, sem que houvesse sido comunicado previamente acerca dos procedimentos diante de quaisquer intercorrências e, de igual modo ausente, também não havia referências disto nas normas internas a ponto de orientá-lo sobre a forma esperada de proceder.

Nenhuma destas exigências que a DGER faz foi mencionada previamente nas normas: comunicação imediata de fato com potencial para interferir nas atividades acadêmicas, para suspender ou interromper a ação de capacitação; informar à Administração sobre situações que repercutam ou possam prejudicar o desempenho satisfatório ou aproveitamento efetivo do período letivo semestral. Ainda no campo das falhas de comunicação, não parece muito prudente ou eficaz a expectativa de que o servidor traga espontaneamente tais problemas à DGER, sem que esta orientação esteja explícita nos normativos. É que além das idiossincrasias pelas quais atribuimos valores e pesos diferentes aos eventos com que nos deparamos no decorrer da vida, não podemos contar com obrigações que sejam presumidas, para o bom andamento das relações e dos trabalhos, elas precisam ser explicitadas. 

Por fim, questiona-se o por quê de a decisão da DGER não entender ou considerar o caso do servidor dentro do contexto de incidência de motivos de força maior e caso fortuito. Conforme a legislação e as normas internas, fatores intervenientes nos resultados acadêmicos e independentes da vontade do servidor são justificativa suficiente para isentá-lo de responsabilidade caso nao obtenha o titulo que motivou o afastamento. O que diferencia a enfermidade que o servidor enfrentou de outros casos fortuitos ou motivos de força maior para que se cobre dele, especificamente, o ressarcimento?


Se um motivo de força maior é suficiente para isentar alguém de responsabilidade em relação ao curso inteiro de 8 semestres, o que ocorre no caso específico para que a DGER tenha decidido não isentar o servidor por somente um único semestre? 

Se a norma é aplicada a quem não termina o curso ou a quem falha em terminar, por que motivo o servidor foi processado 10 meses antes do fim do afastamento? E por que motivo a DGER acolheu a acusação feita contra o servidor, sem , isto é, recepcionou o encaminhamento de "representação" ou qualquer nome que seja, enfim o documento fora do padrão enviado pelo ILB acusando o servidor. 

p.1803 - questiona-se ainda o período indicado pela DGER para o 1º semestre de 2023. Se há vínculo necessario com matrícula em disciplinas, então o ressarcimento deve ser calculado somente com base no período em que havia aula, e não no período inteiro. 

Ainda, sobre o art. 58 do RASF, não está inscrito nesse artigo (nem em nenhum outro) a obrigação aludida pela DGER em sua decisão de que haja constatação de desempenho de atividades acadêmicas com aproveitamento no período analisado. Conforme o despacho reconhece, não havia terminado ainda o afastamento. Portanto, a DGER deveria apontar qual dispositivo do art. 41 (não do 42 ou 43) o servidor descumpriu a ponto de ensejar a punição prevista no art. 58. Ao fazê-lo, a DGER deveria ainda apontar o que exatamente no caso do servido desqualifica sua enfermidade como caso fortuito e motivo de força maior para constituir justificativa suficiente a explicar a não obtenção de crédito.

p. 1804 -

cita competencia delineada no 
- art. 74 do RASF
- art. 58 parágrafo único do anexo IV do RASF
- ADG 17/2021
- PIL 1/2017



